/* RIMLINE Tactical Courtbook: deterministic offline simulation rules for both career modes. */

export type PlayerProgression = { skillPoints: number; shooting: number; playmaking: number; defense: number; athleticism: number; leadership: number; injuryWeeks: number; reputation: number; legacy: number; achievements: string[]; challenge: string };
export type ManagerOperations = { roster: { name: string; role: string; overall: number; morale: number }[]; staff: { name: string; role: string; level: number }[]; scouting: number; tactics: string; draftBoard: string[]; capSpace: number; tradesMade: number; championships: number; legacy: number; achievements: string[]; challenge: string };
export type ScheduleGame = { week: number; home: string; away: string; played: boolean; result: string | null };
export type DraftProspect = { name: string; school: string; position: string; archetype: string; overall: number; potential: number; combine: number; fit: number };
export type PlayoffSeries = { seed: number; opponent: string; wins: number; losses: number; bestOf: number; status: "active" | "won" | "lost" };
export type AwardResult = { name: string; recipient: string; reason: string };
export type PlayoffRound = "first-round" | "conference-semifinal" | "conference-final" | "championship";
export type PlayoffState = { season: number; round: PlayoffRound; series: PlayoffSeries; seriesNumber: number; champion: string | null; eliminated: boolean; history: string[]; seed: number };
export type TradeProposal = { id: string; fromTeam: string; toTeam: string; incomingName: string; incomingSalary: number; outgoingName: string; outgoingSalary: number; yearsRemaining: number; fitScore: number; status: "pending" | "accepted" | "declined"; rationale: string };
export type RookieClass = { season: number; seed: number; prospects: DraftProspect[]; lotteryOrder: string[]; history: string[] };

export const defaultPlayerProgression: PlayerProgression = { skillPoints: 6, shooting: 74, playmaking: 62, defense: 58, athleticism: 69, leadership: 44, injuryWeeks: 0, reputation: 51, legacy: 18, achievements: ["First Rotation Minutes"], challenge: "Become an All-League starter" };
export const defaultManagerOperations: ManagerOperations = { roster: [{ name: "Jayson Tatum", role: "SF", overall: 90, morale: 78 }, { name: "Jaylen Brown", role: "SG", overall: 88, morale: 84 }, { name: "Al Horford", role: "C", overall: 79, morale: 71 }, { name: "Derrick White", role: "PG", overall: 82, morale: 86 }], staff: [{ name: "Mina Okafor", role: "Lead Scout", level: 2 }, { name: "D. Price", role: "Performance Coach", level: 1 }, { name: "I. Chen", role: "Medical Director", level: 1 }], scouting: 64, tactics: "Balanced", draftBoard: ["N. Adeyemi — Two-Way Guard", "R. Bell — Rim Protector", "C. Santos — Shot Creator"], capSpace: 42, tradesMade: 0, championships: 0, legacy: 11, achievements: ["First Front Office Win"], challenge: "Build a top-four defense" };
export const challengeScenarios = ["Become an All-League starter", "Win a championship with one franchise", "Build a top-four defense", "Develop a late-round prospect", "Turn a lottery team into a contender", "Win a title without exceeding the cap"];
export const contractOffers = [{ team: "Boston Celtics", years: 2, annual: 12.5, role: "Starter" }, { team: "New York Knicks", years: 3, annual: 16.2, role: "Franchise piece" }, { team: "Portland Trail Blazers", years: 1, annual: 9.8, role: "Contender rotation" }];
export const relationshipSeeds = [{ name: "Derrick White", role: "Teammate", score: 72, note: "Wants a bigger voice in the offense." }, { name: "Mina Okafor", role: "Agent", score: 64, note: "Tracking the market before the deadline." }, { name: "Donovan Mitchell", role: "Rival", score: 41, note: "The next matchup is personal." }];

export function clampScore(value: number, min = 0, max = 99) { return Math.max(min, Math.min(max, value)); }
export function deterministicPulse(seed: number) { const raw = Math.sin(seed * 12.9898) * 43758.5453; return raw - Math.floor(raw); }
export function trainAttribute(state: PlayerProgression, attribute: keyof Pick<PlayerProgression, "shooting" | "playmaking" | "defense" | "athleticism" | "leadership">): PlayerProgression { if (state.skillPoints <= 0) return state; return { ...state, skillPoints: state.skillPoints - 1, [attribute]: clampScore(state[attribute] + 2) } as PlayerProgression; }
export function resolveInjury(state: PlayerProgression, intensity: "safe" | "normal" | "aggressive"): PlayerProgression { const risk = intensity === "aggressive" ? 2 : intensity === "normal" ? 1 : 0; return { ...state, injuryWeeks: Math.max(0, state.injuryWeeks + risk - 1) }; }
export function evolveLeague<T extends { name: string; overall: number; wins: number; losses: number }>(teams: T[], season: number) { return teams.map((team, index) => ({ ...team, overall: clampScore(team.overall + ((season + index) % 3) - 1), wins: Math.max(0, 41 + ((season * 7 + index * 3) % 16)), losses: Math.max(0, 41 - ((season * 7 + index * 3) % 16)) })); }
export function awardFor(playerPoints: number, wins: number) { return playerPoints >= 22 && wins >= 45 ? "All-League First Team" : playerPoints >= 18 ? "All-League Second Team" : "Reliable Rotation Award"; }

export function buildSeasonSchedule(team: string, opponents: string[], season = 1): ScheduleGame[] { const list = opponents.filter((item) => item !== team); return Array.from({ length: 82 }, (_, index) => { const opponent = list[(index + season) % list.length] || "Boston Celtics"; const home = index % 2 === 0; return { week: index + 1, home: home ? team : opponent, away: home ? opponent : team, played: false, result: null }; }); }
export function resolveScheduleGame(game: ScheduleGame, teamOverall: number, opponentOverall: number, tactics = "Balanced") { const tacticalEdge = tactics === "Run & Gun" ? 2 : tactics === "Lockdown" ? 3 : 0; const margin = teamOverall - opponentOverall + tacticalEdge + ((game.week * 7) % 9) - 4; const teamWon = margin >= 0; return { ...game, played: true, result: teamWon ? `${game.home} W` : `${game.away} W`, teamWon, margin, homeScore: 96 + Math.max(0, margin) + (game.week % 7), awayScore: 96 + Math.max(0, -margin) + ((game.week + 3) % 7) }; }
export function collegeTournamentRound(wins: number, losses: number) { const games = wins + losses; return games >= 28 && wins >= 18 ? Math.min(6, Math.floor((wins - 18) / 2) + 1) : 0; }
export function buildDraftBoard(season: number): DraftProspect[] { const schools = ["Duke", "UConn", "Kansas", "Kentucky", "UCLA", "Gonzaga", "Baylor", "Michigan State"]; const profiles = ["Two-Way Wing", "Rim Protector", "Floor General", "Shot-Creating Wing", "Stretch Big", "Rim Pressure Guard"]; return schools.map((school, index) => ({ name: [`Cameron Ellis`, `Malik Foster`, `Andre Bell`, `Noah Whitaker`, `Isaiah Cole`, `Jalen Brooks`, `Trey Monroe`, `Julian Hayes`][index], school, position: ["SG", "C", "PG", "SF", "PF", "SG", "C", "PG"][index], archetype: profiles[(index + season) % profiles.length], overall: 70 + ((index * 3 + season) % 12), potential: 82 + ((index + season) % 15), combine: 68 + ((index * 5 + season) % 27), fit: 64 + ((index * 7 + season) % 33) })); }
export function assignDraftPick(combineScore: number, teamCount = 30) { const pick = combineScore >= 88 ? 3 : combineScore >= 80 ? 9 : combineScore >= 72 ? 18 : combineScore >= 64 ? 28 : teamCount + 1; return { pick, status: pick <= teamCount ? "drafted" as const : "undrafted" as const }; }
export function buildPlayoffSeries(teams: { name: string; rank: number }[], team: string): PlayoffSeries[] { return teams.filter((item) => item.name !== team).slice(0, 3).map((item, index) => ({ seed: item.rank || index + 1, opponent: item.name, wins: 0, losses: 0, bestOf: 7, status: "active" as const })); }
export function resolvePlayoffGame(series: PlayoffSeries, teamOverall: number, opponentOverall: number, gameNumber: number) { const teamWon = teamOverall + ((gameNumber * 3) % 7) >= opponentOverall + 2; const wins = series.wins + (teamWon ? 1 : 0); const losses = series.losses + (teamWon ? 0 : 1); const status = wins >= 4 ? "won" as const : losses >= 4 ? "lost" as const : "active" as const; return { ...series, wins, losses, status, teamWon }; }
export function calculateAwards(playerName: string, ppg: number, wins: number, championship: boolean): AwardResult[] { return [{ name: "Most Valuable Player", recipient: ppg >= 24 && wins >= 50 ? playerName : "League Leader", reason: "Production plus winning impact" }, { name: "All-League Team", recipient: ppg >= 20 ? playerName : "Rotation Honoree", reason: `${ppg.toFixed(1)} points per game` }, { name: "Finals MVP", recipient: championship ? playerName : "Pending", reason: championship ? "Closed the series under pressure" : "Win the championship to unlock" }]; }
export function applyLifestyleChoice(reputation: number, cash: number, choice: "community" | "luxury" | "focus") { if (choice === "community") return { reputation: clampScore(reputation + 5), cash: cash - 2000, note: "Community work compounds the brand." }; if (choice === "luxury") return { reputation: clampScore(reputation + 1), cash: cash - 9000, note: "The look lands, but the runway gets shorter." }; return { reputation: clampScore(reputation + 2), cash, note: "The work stays visible." }; }
export function negotiateContract(offer: { annual: number; years: number }, leverage: number) { const bonus = leverage >= 80 ? 1.8 : leverage >= 65 ? 0.8 : 0; return { ...offer, annual: Number((offer.annual + bonus).toFixed(1)), years: leverage >= 85 ? offer.years + 1 : offer.years }; }
export function applyRelationship(score: number, action: "listen" | "compete" | "distance") { return clampScore(score + (action === "listen" ? 6 : action === "compete" ? 2 : -4)); }
export function managerRotation(roster: { name: string; role: string; overall: number; morale: number }[], focus: string) { return [...roster].sort((a, b) => (focus === "Lockdown" ? b.morale - a.morale : b.overall - a.overall)).map((player, index) => ({ ...player, role: index === 0 ? "Starter" : index < 5 ? "Rotation" : "Bench" })); }
export function transactionValue(overall: number, ageFactor: number) { return clampScore(Math.round(overall * 0.75 + ageFactor * 0.25), 40, 99); }
export function unlockAchievements(current: string[], metrics: { wins: number; overall: number; legacy: number; championship: boolean }) { const next = [...current]; if (metrics.wins >= 50 && !next.includes("50-Win Season")) next.push("50-Win Season"); if (metrics.overall >= 90 && !next.includes("All-League Threshold")) next.push("All-League Threshold"); if (metrics.legacy >= 50 && !next.includes("Legacy in Motion")) next.push("Legacy in Motion"); if (metrics.championship && !next.includes("Champion")) next.push("Champion"); return next; }

export function createPlayoffState(season: number, team: string, opponent: string, seed = 1): PlayoffState { return { season, round: "first-round", series: { seed, opponent, wins: 0, losses: 0, bestOf: 7, status: "active" }, seriesNumber: 1, champion: null, eliminated: false, history: [], seed }; }
export function playoffRoundLabel(round: PlayoffRound) { return round === "first-round" ? "FIRST ROUND" : round === "conference-semifinal" ? "CONFERENCE SEMIS" : round === "conference-final" ? "CONFERENCE FINALS" : "CHAMPIONSHIP"; }
export function advancePlayoffRound(state: PlayoffState, team: string, opponent: string): PlayoffState { const nextRound: PlayoffRound = state.round === "first-round" ? "conference-semifinal" : state.round === "conference-semifinal" ? "conference-final" : state.round === "conference-final" ? "championship" : "championship"; const completed = state.round === "championship"; return { ...state, round: nextRound, series: { seed: Math.max(1, state.seed - 1), opponent, wins: 0, losses: 0, bestOf: 7, status: "active" }, seriesNumber: state.seriesNumber + 1, champion: completed ? team : null, history: [...state.history, `${playoffRoundLabel(state.round)} won over ${state.series.opponent}`] }; }
export function resolvePlayoffStateGame(state: PlayoffState, teamOverall: number, opponentOverall: number, gameNumber: number, team: string, nextOpponent: string) { const resolved = resolvePlayoffGame(state.series, teamOverall, opponentOverall, gameNumber); const history = [...state.history, `${playoffRoundLabel(state.round)} / GAME ${gameNumber}: ${resolved.teamWon ? team : state.series.opponent}`]; if (resolved.status === "lost") return { ...state, series: resolved, eliminated: true, history }; if (resolved.status === "won") return advancePlayoffRound({ ...state, series: resolved, history }, team, nextOpponent); return { ...state, series: resolved, history }; }

export function generateRookieClass(season: number, seed = season * 97 + 11, count = 12): RookieClass { const schools = ["Duke", "UConn", "Kansas", "Kentucky", "UCLA", "Gonzaga", "Baylor", "Michigan State", "Arizona", "Villanova", "Houston", "Iowa State"]; const archetypes = ["Two-Way Wing", "Rim Protector", "Floor General", "Shot-Creating Wing", "Stretch Big", "Rim Pressure Guard"]; const names = ["Cameron Ellis", "Malik Foster", "Andre Bell", "Noah Whitaker", "Isaiah Cole", "Jalen Brooks", "Trey Monroe", "Julian Hayes", "Marcus Vale", "Kobe Mercer", "Darius Snow", "Eli Navarro"]; const prospects = Array.from({ length: count }, (_, index) => { const pulse = deterministicPulse(seed + index * 17); const overall = 66 + ((Math.floor(pulse * 1000) + season + index * 3) % 19); return { name: `${names[index % names.length]} '0${(season + index) % 10}`, school: schools[(index + season) % schools.length], position: ["PG", "SG", "SF", "PF", "C"][index % 5], archetype: archetypes[(index + season) % archetypes.length], overall, potential: clampScore(overall + 10 + ((index + season) % 14)), combine: 62 + ((Math.floor(pulse * 100) + index * 5) % 35), fit: 58 + ((Math.floor(pulse * 1000) + index * 7) % 42) }; }); return { season, seed, prospects, lotteryOrder: [], history: [`Generated ${count} prospects for season ${season} from seed ${seed}.`] }; }
export function drawDraftLottery(teams: { name: string; wins: number; losses: number }[], season: number, seed = season * 131): string[] { return [...teams].sort((a, b) => { const aWeight = Math.max(1, 82 - a.wins) + Math.floor(deterministicPulse(seed + a.wins) * 10); const bWeight = Math.max(1, 82 - b.wins) + Math.floor(deterministicPulse(seed + b.wins) * 10); return bWeight - aWeight; }).map((team) => team.name); }
export function buildTradeProposal(seed: number, fromTeam: string, toTeam: string, roster: { name: string; overall: number; salary?: number }[], capSpace: number): TradeProposal | null { if (!roster.length) return null; const outgoing = roster[Math.floor(deterministicPulse(seed) * roster.length) % roster.length]; const incomingOverall = clampScore(outgoing.overall + Math.round(deterministicPulse(seed + 1) * 8) - 4, 65, 96); const outgoingSalary = outgoing.salary ?? Math.max(2, Number((outgoing.overall / 7.2).toFixed(1))); const incomingSalary = Number((outgoingSalary * (0.9 + deterministicPulse(seed + 2) * 0.2)).toFixed(1)); const legal = Math.abs(incomingSalary - outgoingSalary) <= Math.max(5, outgoingSalary * 0.25) || capSpace >= incomingSalary - outgoingSalary; if (!legal) return null; const fitScore = clampScore(Math.round((incomingOverall + capSpace + deterministicPulse(seed + 3) * 20) / 2)); return { id: `proposal-${seed}`, fromTeam, toTeam, incomingName: `${["Tyrese", "Malik", "Derrick", "Cameron"][seed % 4]} ${["Vale", "Grant", "Foster", "Ellis"][(seed + 1) % 4]}`, incomingSalary, outgoingName: outgoing.name, outgoingSalary, yearsRemaining: 1 + (seed % 4), fitScore, status: "pending", rationale: fitScore >= 80 ? "A clean fit for the current identity and cap sheet." : "The talent is real, but the rotation needs a deliberate adjustment." }; }
