/* RIMLINE Tactical Courtbook simulation rules: deterministic, offline-safe systems shared by Player and Manager careers. */

export type PlayerProgression = { skillPoints: number; shooting: number; playmaking: number; defense: number; athleticism: number; leadership: number; injuryWeeks: number; reputation: number; legacy: number; achievements: string[]; challenge: string };
export type ManagerOperations = { roster: { name: string; role: string; overall: number; morale: number }[]; staff: { name: string; role: string; level: number }[]; scouting: number; tactics: string; draftBoard: string[]; capSpace: number; tradesMade: number; championships: number; legacy: number; achievements: string[]; challenge: string };

export const defaultPlayerProgression: PlayerProgression = { skillPoints: 6, shooting: 74, playmaking: 62, defense: 58, athleticism: 69, leadership: 44, injuryWeeks: 0, reputation: 51, legacy: 18, achievements: ["First Rotation Minutes"], challenge: "Become an All-League starter" };
export const defaultManagerOperations: ManagerOperations = { roster: [{ name: "A. Holloway", role: "PG", overall: 82, morale: 78 }, { name: "J. Walsh", role: "PF", overall: 80, morale: 84 }, { name: "Joel Vickers", role: "C", overall: 79, morale: 71 }, { name: "H. González", role: "SF", overall: 77, morale: 86 }], staff: [{ name: "Mina Okafor", role: "Lead Scout", level: 2 }, { name: "D. Price", role: "Performance Coach", level: 1 }, { name: "I. Chen", role: "Medical Director", level: 1 }], scouting: 64, tactics: "Balanced", draftBoard: ["N. Adeyemi — Two-Way Guard", "R. Bell — Rim Protector", "C. Santos — Shot Creator"], capSpace: 42, tradesMade: 0, championships: 0, legacy: 11, achievements: ["First Front Office Win"], challenge: "Build a top-four defense" };
export const challengeScenarios = ["Become an All-League starter", "Win a championship with one franchise", "Build a top-four defense", "Develop a late-round prospect"];
export const contractOffers = [{ team: "Boston Comets", years: 2, annual: 12.5, role: "Starter" }, { team: "New York Empire", years: 3, annual: 16.2, role: "Franchise piece" }, { team: "Portland Lumber", years: 1, annual: 9.8, role: "Contender rotation" }];
export const relationshipSeeds = [{ name: "J. Walsh", role: "Teammate", score: 72, note: "Wants a bigger voice in the offense." }, { name: "Mina Okafor", role: "Agent", score: 64, note: "Tracking the market before the deadline." }, { name: "C. Bell", role: "Rival", score: 41, note: "The next matchup is personal." }];

export function clampScore(value: number, min = 0, max = 99) { return Math.max(min, Math.min(max, value)); }
export function trainAttribute(state: PlayerProgression, attribute: keyof Pick<PlayerProgression, "shooting" | "playmaking" | "defense" | "athleticism" | "leadership">): PlayerProgression { if (state.skillPoints <= 0) return state; return { ...state, skillPoints: state.skillPoints - 1, [attribute]: clampScore(state[attribute] + 2) } as PlayerProgression; }
export function resolveInjury(state: PlayerProgression, intensity: "safe" | "normal" | "aggressive"): PlayerProgression { const risk = intensity === "aggressive" ? 2 : intensity === "normal" ? 1 : 0; return { ...state, injuryWeeks: Math.max(0, state.injuryWeeks + risk - 1) }; }
export function evolveLeague(teams: { name: string; overall: number; wins: number; losses: number }[], season: number) { return teams.map((team, index) => ({ ...team, overall: clampScore(team.overall + ((season + index) % 3) - 1), wins: Math.max(0, 41 + ((season * 7 + index * 3) % 16)), losses: Math.max(0, 41 - ((season * 7 + index * 3) % 16)) })); }
export function awardFor(playerPoints: number, wins: number) { return playerPoints >= 22 && wins >= 45 ? "All-League First Team" : playerPoints >= 18 ? "All-League Second Team" : "Reliable Rotation Award"; }
