/* RIMLINE Tactical Courtbook
   Career entry is mode-first: Player and Manager are separate experiences.
   Each game resolves into a full two-team box score before the next week begins. */
import { useEffect, useMemo, useState } from "react";
import { BarChart3, BriefcaseBusiness, ChevronLeft, ChevronRight, Circle, Dumbbell, Flame, Home as HomeIcon, LayoutDashboard, LineChart, Medal, Menu, Play, RefreshCw, RotateCcw, Save, Shield, Sparkles, Star, Trophy, Users, WalletCards, Zap } from "lucide-react";
import { type CareerSave, clearCareerSave, getCareerSave, migrateLegacySave, readLocalFallback, saveCareerSave, writeLocalFallback } from "@/lib/careerDb";

type CareerScreen = "start" | "create-player" | "create-manager" | "player" | "manager" | "boxscore" | "event" | "offseason";
type PlayerTab = "home" | "league" | "training" | "life" | "stats";
type ManagerTab = "office" | "roster" | "league";
type Mode = "player" | "manager";
type Player = { name: string; position: string; archetype: string; overall: number; energy: number; cash: number; fans: number; game: number; wins: number; losses: number; ppg: number; rpg: number; apg: number; form: number };
type Team = { rank: number; name: string; city: string; overall: number; wins: number; losses: number; tone: string };
type BoxRow = { role: string; name: string; min: number; pts: number; reb: number; ast: number; stl: number; blk: number; starter?: boolean };
type BoxScore = { home: string; away: string; homeScore: number; awayScore: number; winner: string; homeRows: BoxRow[]; awayRows: BoxRow[]; week: number; mode: Mode };
type WeeklyEvent = { id: string; title: string; kicker: string; body: string; source: string; options: { id: string; label: string; detail: string }[]; mode: Mode };
type SeasonSummary = { season: number; record: string; highlight: string; reward: string; mode: Mode };

const demoBox: BoxScore = { home: "Boston Comets", away: "Charlotte Monarchs", homeScore: 118, awayScore: 112, winner: "Boston Comets", week: 28, mode: "player", homeRows: [{ role: "SG", name: "Malik Carter", min: 39, pts: 38, reb: 6, ast: 8, stl: 2, blk: 0, starter: true }, { role: "PF", name: "J. Walsh", min: 33, pts: 14, reb: 9, ast: 4, stl: 1, blk: 1 }, { role: "C", name: "Joel Vickers", min: 29, pts: 11, reb: 12, ast: 2, stl: 1, blk: 2 }, { role: "SF", name: "H. González", min: 31, pts: 14, reb: 5, ast: 5, stl: 2, blk: 0 }, { role: "PG", name: "K. Norton", min: 27, pts: 9, reb: 3, ast: 7, stl: 1, blk: 0 }, { role: "SG", name: "R. Dorsey", min: 18, pts: 7, reb: 2, ast: 2, stl: 0, blk: 0 }, { role: "PF", name: "M. Okafor", min: 15, pts: 5, reb: 4, ast: 1, stl: 0, blk: 1 }, { role: "C", name: "L. Garza", min: 11, pts: 3, reb: 3, ast: 0, stl: 0, blk: 0 }, { role: "SG", name: "T. Quinn", min: 8, pts: 2, reb: 1, ast: 1, stl: 0, blk: 0 }, { role: "PG", name: "D. Reed", min: 5, pts: 0, reb: 1, ast: 1, stl: 0, blk: 0 }], awayRows: opponentRows(true) };
const initialPlayer: Player = { name: "Malik Carter", position: "SG", archetype: "Pure Shooter", overall: 84, energy: 100, cash: 24860, fans: 342000, game: 28, wins: 18, losses: 9, ppg: 19.6, rpg: 4.8, apg: 3.9, form: 76 };
const playerEvents: WeeklyEvent[] = [{ id: "brand-call", title: "The Brand Call", kicker: "LIFE / OPPORTUNITY", body: "A regional label wants you in a campaign before the next road trip. It is good money, but the shoot costs a recovery day.", source: "Your agent is waiting for an answer.", options: [{ id: "take-deal", label: "Take the deal", detail: "+$4,000 cash • +12K followers • -8 energy" }, { id: "protect-work", label: "Protect the work", detail: "+4 form • +2 overall momentum" }] , mode: "player" }, { id: "locker-room", title: "Locker Room Temperature", kicker: "TEAM / PRESSURE", body: "A veteran calls for a players-only meeting after a flat loss. You can lead it, or stay late for extra reps.", source: "One choice changes the room. Both change you.", options: [{ id: "lead-room", label: "Lead the room", detail: "+5 chemistry • +3 morale" }, { id: "extra-reps", label: "Stay for reps", detail: "+3 form • -12 energy" }], mode: "player" }, { id: "rival-quote", title: "The Rival Quote", kicker: "MEDIA / CONSEQUENCE", body: "A rival says your scoring is empty calories. The clip is already moving through the league feed.", source: "The next matchup just got louder.", options: [{ id: "answer-court", label: "Answer on court", detail: "+4 form • +10K followers" }, { id: "stay-quiet", label: "Stay quiet", detail: "+10 energy • -2 brand heat" }], mode: "player" }];
const managerEvents: WeeklyEvent[] = [{ id: "trade-rumor", title: "Trade Rumor: Vickers", kicker: "FRONT OFFICE / INTEL", body: "A contender is calling about Joel Vickers. The offer is future flexibility, but the locker room trusts your starting five.", source: "The deadline is six weeks away.", options: [{ id: "hold-line", label: "Hold the line", detail: "+4 chemistry • +2 morale" }, { id: "shop-vickers", label: "Explore the market", detail: "+6 scouting • -4 chemistry" }], mode: "manager" }, { id: "rookie-breakout", title: "Rookie Breakout", kicker: "DEVELOPMENT / SIGNAL", body: "A second-unit guard is forcing the issue in practice. Give them a bigger role now, or keep the veteran rotation stable.", source: "Your staff wants a clear direction.", options: [{ id: "promote-rookie", label: "Open the rotation", detail: "+5 morale • +3 scouting" }, { id: "trust-vets", label: "Trust the veterans", detail: "+4 chemistry • +2 defense" }], mode: "manager" }, { id: "owner-pressure", title: "Owner Pressure", kicker: "OWNERSHIP / EXPECTATION", body: "The owner wants a statement win this week. You can push the pace, or protect the team from a volatile game plan.", source: "Expectations are now part of the job.", options: [{ id: "push-pace", label: "Push the pace", detail: "+5 morale • -4 defense" }, { id: "protect-floor", label: "Protect the floor", detail: "+4 defense • +2 scouting" }], mode: "manager" }];
const initialSeason = { season: 1, eventHistory: [] as string[], lastEventId: "" };
const demoSummary: SeasonSummary = { season: 1, record: "42-40", highlight: "Malik Carter closed the year at 21.4 PPG and made the rotation permanent.", reward: "Choose how to spend the offseason.", mode: "player" };
const teams: Team[] = [
  { rank: 1, name: "Chicago Fury", city: "CHI", overall: 81, wins: 52, losses: 24, tone: "#f05c39" }, { rank: 2, name: "Washington Sentinels", city: "WAS", overall: 82, wins: 50, losses: 26, tone: "#f2b84b" }, { rank: 3, name: "Orlando Comets", city: "ORL", overall: 81, wins: 48, losses: 28, tone: "#94a3b8" }, { rank: 4, name: "Toronto Huskies", city: "TOR", overall: 81, wins: 46, losses: 30, tone: "#93c5fd" }, { rank: 5, name: "Detroit Steel", city: "DET", overall: 82, wins: 44, losses: 32, tone: "#c9a66b" }, { rank: 6, name: "Charlotte Monarchs", city: "CHA", overall: 81, wins: 42, losses: 34, tone: "#b07bf3" }, { rank: 7, name: "Brooklyn Phantoms", city: "BKN", overall: 82, wins: 40, losses: 36, tone: "#2dd4bf" }, { rank: 8, name: "Boston Comets", city: "BOS", overall: 80, wins: 18, losses: 9, tone: "#ff6a00" },
];
const playerNav: { id: PlayerTab; label: string; icon: typeof HomeIcon }[] = [{ id: "home", label: "Home", icon: HomeIcon }, { id: "training", label: "Training", icon: Dumbbell }, { id: "league", label: "League", icon: Trophy }, { id: "life", label: "Life", icon: Star }, { id: "stats", label: "Stats", icon: BarChart3 }];
const managerNav: { id: ManagerTab; label: string; icon: typeof BriefcaseBusiness }[] = [{ id: "office", label: "Office", icon: BriefcaseBusiness }, { id: "roster", label: "Roster", icon: Users }, { id: "league", label: "League", icon: Trophy }];

function money(value: number) { return `$${value.toLocaleString("en-US")}`; }
function shortFans(value: number) { return value >= 1000000 ? `${(value / 1000000).toFixed(2)}M` : `${(value / 1000).toFixed(0)}K`; }
function loadJson<T>(key: string, fallback: T): T { try { return { ...fallback as object, ...JSON.parse(localStorage.getItem(key) || "{}") } as T; } catch { return fallback; } }
function getWeeklyEvent(mode: Mode, game: number, season: number): WeeklyEvent { const pool = mode === "player" ? playerEvents : managerEvents; return pool[(game + season) % pool.length]; }
function clamp(value: number, min = 0, max = 99) { return Math.max(min, Math.min(max, value)); }

export default function Home() {
  const queryScreen = new URLSearchParams(window.location.search).get("screen") as CareerScreen | null;
  const hasCareer = localStorage.getItem("rimline-career-started") === "true";
  const [screen, setScreen] = useState<CareerScreen>(queryScreen === "start" || queryScreen === "create-player" || queryScreen === "create-manager" || queryScreen === "boxscore" || queryScreen === "event" || queryScreen === "offseason" ? queryScreen : (hasCareer ? (localStorage.getItem("rimline-mode") === "manager" ? "manager" : "player") : "start"));
  const [mode, setMode] = useState<Mode>((localStorage.getItem("rimline-mode") as Mode) || "player");
  const [playerTab, setPlayerTab] = useState<PlayerTab>("home");
  const [managerTab, setManagerTab] = useState<ManagerTab>("office");
  const [player, setPlayer] = useState<Player>(() => loadJson("rimline-player", initialPlayer));
  const [managerName, setManagerName] = useState(() => localStorage.getItem("rimline-manager-name") || "Jordan Rivera");
  const [managerPhilosophy, setManagerPhilosophy] = useState(() => localStorage.getItem("rimline-manager-philosophy") || "Player Development");
  const [toast, setToast] = useState("");
  const [lastBox, setLastBox] = useState<BoxScore | null>(() => queryScreen === "boxscore" ? demoBox : null);
  const [managerFocus, setManagerFocus] = useState("Balanced");
  const [managerState, setManagerState] = useState(() => loadJson("rimline-manager-state", { chemistry: 72, morale: 81, defense: 78, scouting: 64, teamWins: 18, teamLosses: 9 }));
  const [seasonState, setSeasonState] = useState(() => loadJson("rimline-season", initialSeason));
  const [weeklyEvent, setWeeklyEvent] = useState<WeeklyEvent | null>(() => queryScreen === "event" ? getWeeklyEvent(mode, player.game, seasonState.season) : null);
  const [seasonSummary, setSeasonSummary] = useState<SeasonSummary | null>(() => queryScreen === "offseason" ? demoSummary : null);
  const [isHydrated, setIsHydrated] = useState(false);
  const [saveStatus, setSaveStatus] = useState<"loading" | "saved" | "fallback">("loading");

  useEffect(() => { localStorage.setItem("rimline-player", JSON.stringify(player)); }, [player]);
  useEffect(() => { localStorage.setItem("rimline-mode", mode); }, [mode]);
  useEffect(() => { localStorage.setItem("rimline-manager-state", JSON.stringify(managerState)); }, [managerState]);
  useEffect(() => { localStorage.setItem("rimline-season", JSON.stringify(seasonState)); }, [seasonState]);
  useEffect(() => { let active = true; (async () => { const defaults: CareerSave = { schemaVersion: 1, updatedAt: new Date().toISOString(), mode, screen, playerTab, managerTab, player: player as unknown as Record<string, unknown>, managerName, managerPhilosophy, managerFocus, managerState: managerState as unknown as Record<string, unknown>, seasonState: seasonState as unknown as Record<string, unknown>, lastBox: lastBox as unknown as Record<string, unknown> | null, weeklyEvent: weeklyEvent as unknown as Record<string, unknown> | null, seasonSummary: seasonSummary as unknown as Record<string, unknown> | null }; try { const result = await migrateLegacySave(defaults); const saved = result.save || readLocalFallback(); if (!active) return; if (saved && !result.migrated) { setMode(saved.mode); setScreen(saved.screen as CareerScreen); setPlayerTab(saved.playerTab as PlayerTab); setManagerTab(saved.managerTab as ManagerTab); setPlayer(saved.player as unknown as Player); setManagerName(saved.managerName); setManagerPhilosophy(saved.managerPhilosophy); setManagerFocus(saved.managerFocus); setManagerState(saved.managerState as typeof managerState); setSeasonState(saved.seasonState as typeof seasonState); setLastBox(saved.lastBox as BoxScore | null); setWeeklyEvent(saved.weeklyEvent as WeeklyEvent | null); setSeasonSummary(saved.seasonSummary as SeasonSummary | null); } setSaveStatus("saved"); setIsHydrated(true); if (result.migrated) setToast("Legacy career migrated to a durable offline file."); } catch { const fallback = readLocalFallback(); if (fallback && active) { setMode(fallback.mode); setScreen(fallback.screen as CareerScreen); setPlayer(fallback.player as unknown as Player); setManagerState(fallback.managerState as typeof managerState); setSeasonState(fallback.seasonState as typeof seasonState); setLastBox(fallback.lastBox as BoxScore | null); setWeeklyEvent(fallback.weeklyEvent as WeeklyEvent | null); setSeasonSummary(fallback.seasonSummary as SeasonSummary | null); } if (active) { setSaveStatus("fallback"); setIsHydrated(true); } } })(); return () => { active = false; }; }, []);
  useEffect(() => { if (!isHydrated) return; const timer = window.setTimeout(() => { const save: CareerSave = { schemaVersion: 1, updatedAt: new Date().toISOString(), mode, screen, playerTab, managerTab, player: player as unknown as Record<string, unknown>, managerName, managerPhilosophy, managerFocus, managerState: managerState as unknown as Record<string, unknown>, seasonState: seasonState as unknown as Record<string, unknown>, lastBox: lastBox as unknown as Record<string, unknown> | null, weeklyEvent: weeklyEvent as unknown as Record<string, unknown> | null, seasonSummary: seasonSummary as unknown as Record<string, unknown> | null }; saveCareerSave(save).then(() => setSaveStatus("saved")).catch(() => { writeLocalFallback(save); setSaveStatus("fallback"); }); }, 350); return () => window.clearTimeout(timer); }, [isHydrated, mode, screen, playerTab, managerTab, player, managerName, managerPhilosophy, managerFocus, managerState, seasonState, lastBox, weeklyEvent, seasonSummary]);
  useEffect(() => { if (!toast) return; const timer = window.setTimeout(() => setToast(""), 2600); return () => window.clearTimeout(timer); }, [toast]);
  const nextOpponent = useMemo(() => teams[(player.game + 1) % teams.length], [player.game]);

  function chooseMode(next: Mode) { setMode(next); setScreen(next === "player" ? "create-player" : "create-manager"); }
  function beginPlayer(name: string, position: string, archetype: string) { setPlayer((current) => ({ ...current, name: name.trim() || "Malik Carter", position, archetype })); localStorage.setItem("rimline-career-started", "true"); localStorage.setItem("rimline-mode", "player"); setMode("player"); setPlayerTab("home"); setScreen("player"); setToast("Player file created. Earn the next minute."); }
  function beginManager(name: string, philosophy: string) { const clean = name.trim() || "Jordan Rivera"; setManagerName(clean); setManagerPhilosophy(philosophy); localStorage.setItem("rimline-career-started", "true"); localStorage.setItem("rimline-mode", "manager"); localStorage.setItem("rimline-manager-name", clean); localStorage.setItem("rimline-manager-philosophy", philosophy); setMode("manager"); setManagerTab("office"); setScreen("manager"); setToast("Front office opened. Shape the culture."); }
  function simulateGame() {
    const boost = player.energy > 60 ? 3 : 0; const performance = player.form + boost + Math.round(Math.random() * 16 - 8); const win = performance >= 74; const points = Math.max(12, Math.round(player.ppg + performance / 10 + Math.random() * 9)); const opponent = nextOpponent.name;
    const homeScore = win ? 118 : 106; const awayScore = win ? 112 : 111;
    setPlayer((current) => ({ ...current, game: Math.min(82, current.game + 1), wins: current.wins + (win ? 1 : 0), losses: current.losses + (win ? 0 : 1), energy: Math.max(22, current.energy - 18), fans: current.fans + (win ? 420 : 160), cash: current.cash + (win ? 1250 : 650), ppg: Number(((current.ppg * 0.94 + points * 0.06)).toFixed(1)), form: Math.min(97, Math.max(48, current.form + (win ? 4 : -3))) }));
    setLastBox({ home: "Boston Comets", away: opponent, homeScore, awayScore, winner: win ? "Boston Comets" : opponent, week: player.game, mode: "player", homeRows: boxRows(player.name, points, win), awayRows: opponentRows(win) }); setScreen("boxscore");
  }
  function simulateManagerGame() { const win = managerState.defense + managerState.chemistry + (managerFocus === "Lockdown" ? 10 : 0) >= 154; const homeScore = win ? 106 : 98; const awayScore = win ? 99 : 111; setManagerState((current) => ({ ...current, teamWins: current.teamWins + (win ? 1 : 0), teamLosses: current.teamLosses + (win ? 0 : 1), morale: Math.min(99, current.morale + (win ? 4 : -2)) })); setLastBox({ home: "Boston Comets", away: nextOpponent.name, homeScore, awayScore, winner: win ? "Boston Comets" : nextOpponent.name, week: player.game, mode: "manager", homeRows: boxRows("A. Holloway", win ? 22 : 14, win), awayRows: opponentRows(win) }); setScreen("boxscore"); }
  function continueWeek() { setLastBox(null); if (player.game >= 82) { const record = mode === "player" ? `${player.wins}-${player.losses}` : `${managerState.teamWins}-${managerState.teamLosses}`; setSeasonSummary({ season: seasonState.season, record, highlight: mode === "player" ? `${player.name} closed the year at ${player.ppg.toFixed(1)} PPG.` : `The Comets finished with a ${managerState.defense} defensive grade.`, reward: mode === "player" ? "Choose how to spend the offseason." : "Choose the next front-office mandate.", mode }); setScreen("offseason"); return; } const nextEvent = getWeeklyEvent(mode, player.game, seasonState.season); setWeeklyEvent(nextEvent); setSeasonState((current) => ({ ...current, lastEventId: nextEvent.id })); setScreen("event"); }
  function train(type: string) { if (player.energy < 20) { setToast("Not enough energy. Recover before training."); return; } setPlayer((current) => ({ ...current, energy: current.energy - 20, overall: Math.min(99, current.overall + 1), form: Math.min(97, current.form + 2) })); setToast(`${type} complete. The work shows up next game.`); }
  function managerAction(action: string) { setManagerState((current) => ({ ...current, chemistry: Math.min(99, current.chemistry + (action === "chemistry" ? 5 : 0)), defense: Math.min(99, current.defense + (action === "defense" ? 4 : 0)), scouting: Math.min(99, current.scouting + (action === "scouting" ? 5 : 0)) })); setToast(`${action[0].toUpperCase() + action.slice(1)} plan applied.`); }
  function resolveEvent(choiceId: string) { if (!weeklyEvent) return; if (mode === "player") { setPlayer((current) => { const next = { ...current }; if (choiceId === "take-deal") { next.cash += 4000; next.fans += 12000; next.energy = Math.max(10, next.energy - 8); } if (choiceId === "protect-work") { next.form = clamp(next.form + 4, 40, 97); next.overall = clamp(next.overall + 1, 1, 99); } if (choiceId === "extra-reps") { next.form = clamp(next.form + 3, 40, 97); next.energy = Math.max(10, next.energy - 12); } if (choiceId === "answer-court") { next.form = clamp(next.form + 4, 40, 97); next.fans += 10000; } if (choiceId === "stay-quiet") { next.energy = Math.min(100, next.energy + 10); } return next; }); } else { setManagerState((current) => ({ ...current, chemistry: clamp(current.chemistry + (choiceId === "lead-room" || choiceId === "hold-line" || choiceId === "trust-vets" ? 4 : choiceId === "shop-vickers" ? -4 : 0)), morale: clamp(current.morale + (choiceId === "lead-room" || choiceId === "promote-rookie" || choiceId === "push-pace" ? 5 : choiceId === "hold-line" ? 2 : 0)), defense: clamp(current.defense + (choiceId === "trust-vets" || choiceId === "protect-floor" ? 4 : choiceId === "push-pace" ? -4 : 0)), scouting: clamp(current.scouting + (choiceId === "shop-vickers" || choiceId === "promote-rookie" || choiceId === "protect-floor" ? 4 : 0)) })); } setSeasonState((current) => ({ ...current, eventHistory: [...current.eventHistory, weeklyEvent.id] })); setWeeklyEvent(null); setScreen(mode === "player" ? "player" : "manager"); setToast("Decision logged. The week moves with you."); }
  function advanceOffseason(choiceId: string) { if (!seasonSummary) return; if (mode === "player") { setPlayer((current) => ({ ...current, game: 0, wins: 0, losses: 0, energy: 100, form: clamp(current.form + (choiceId === "skill-camp" ? 7 : 2), 40, 97), overall: clamp(current.overall + (choiceId === "skill-camp" ? 2 : 1), 1, 99), cash: current.cash + (choiceId === "negotiate" ? 5000 : 1500) })); } else { setManagerState((current) => ({ ...current, teamWins: 0, teamLosses: 0, chemistry: clamp(current.chemistry + (choiceId === "development-summit" ? 6 : 1)), morale: clamp(current.morale + (choiceId === "reset-culture" ? 6 : 1)), defense: clamp(current.defense + (choiceId === "defensive-blueprint" ? 6 : 1)), scouting: clamp(current.scouting + (choiceId === "roster-audit" ? 7 : 2)) })); } setSeasonState((current) => ({ season: current.season + 1, eventHistory: [], lastEventId: "" })); setSeasonSummary(null); setScreen(mode === "player" ? "player" : "manager"); setToast(`Season ${seasonState.season + 1} is live. The standard is higher.`); }
  async function saveNow() { const save: CareerSave = { schemaVersion: 1, updatedAt: new Date().toISOString(), mode, screen, playerTab, managerTab, player: player as unknown as Record<string, unknown>, managerName, managerPhilosophy, managerFocus, managerState: managerState as unknown as Record<string, unknown>, seasonState: seasonState as unknown as Record<string, unknown>, lastBox: lastBox as unknown as Record<string, unknown> | null, weeklyEvent: weeklyEvent as unknown as Record<string, unknown> | null, seasonSummary: seasonSummary as unknown as Record<string, unknown> | null }; try { await saveCareerSave(save); setSaveStatus("saved"); setToast("Career file saved offline."); } catch { writeLocalFallback(save); setSaveStatus("fallback"); setToast("IndexedDB is unavailable. Local recovery copy saved."); } }
  async function loadNow() { try { const saved = await getCareerSave(); if (!saved) { setToast("No IndexedDB career file found."); return; } setMode(saved.mode); setScreen(saved.screen as CareerScreen); setPlayerTab(saved.playerTab as PlayerTab); setManagerTab(saved.managerTab as ManagerTab); setPlayer(saved.player as unknown as Player); setManagerName(saved.managerName); setManagerPhilosophy(saved.managerPhilosophy); setManagerFocus(saved.managerFocus); setManagerState(saved.managerState as typeof managerState); setSeasonState(saved.seasonState as typeof seasonState); setLastBox(saved.lastBox as BoxScore | null); setWeeklyEvent(saved.weeklyEvent as WeeklyEvent | null); setSeasonSummary(saved.seasonSummary as SeasonSummary | null); setSaveStatus("saved"); setToast("Career file loaded from IndexedDB."); } catch { const fallback = readLocalFallback(); if (fallback) { setMode(fallback.mode); setScreen(fallback.screen as CareerScreen); setPlayerTab(fallback.playerTab as PlayerTab); setManagerTab(fallback.managerTab as ManagerTab); setPlayer(fallback.player as unknown as Player); setManagerName(fallback.managerName); setManagerPhilosophy(fallback.managerPhilosophy); setManagerFocus(fallback.managerFocus); setManagerState(fallback.managerState as typeof managerState); setSeasonState(fallback.seasonState as typeof seasonState); setLastBox(fallback.lastBox as BoxScore | null); setWeeklyEvent(fallback.weeklyEvent as WeeklyEvent | null); setSeasonSummary(fallback.seasonSummary as SeasonSummary | null); setSaveStatus("fallback"); setToast("Recovery copy loaded from local storage."); } else { setSaveStatus("fallback"); setToast("Could not open IndexedDB and no recovery copy exists."); } } }
  async function resetGame() { localStorage.clear(); try { await clearCareerSave(); } catch { /* keep the local fallback path available */ } setPlayer(initialPlayer); setLastBox(null); setWeeklyEvent(null); setSeasonSummary(null); setSeasonState(initialSeason); setMode("player"); setScreen("start"); setToast("Career file cleared. Choose a new path."); }

  if (screen === "start") return <><StartScreen onChoose={chooseMode} /><div className="reset-button-wrap"><button className="reset-button" onClick={resetGame} title="Reset career"><RotateCcw size={14} /></button></div></>;
  if (screen === "create-player") return <CreatePlayerScreen onBack={() => setScreen("start")} onCreate={beginPlayer} />;
  if (screen === "create-manager") return <CreateManagerScreen onBack={() => setScreen("start")} onCreate={beginManager} />;
  if (screen === "boxscore" && lastBox) return <BoxScoreScreen box={lastBox} onContinue={continueWeek} />;
  if (screen === "event" && weeklyEvent) return <WeeklyEventScreen event={weeklyEvent} week={player.game} season={seasonState.season} onChoose={resolveEvent} />;
  if (screen === "offseason" && seasonSummary) return <OffseasonScreen summary={seasonSummary} onChoose={advanceOffseason} />;

  return <div className="app-shell"><header className="topbar"><div className="brand-lockup"><img className="brand-logo" src="/manus-storage/rimline-mark_489959e3.png" alt="" /><span>RIM<span>LINE</span></span></div><div className="top-actions"><div className="resource"><WalletCards size={15} /><strong>{money(player.cash)}</strong></div><div className="resource energy"><Zap size={15} /><strong>{player.energy}</strong></div><span className={`save-indicator ${saveStatus}`} title={saveStatus === "saved" ? "Saved offline" : saveStatus === "fallback" ? "Recovery copy active" : "Loading save"}>{saveStatus === "saved" ? "FILE SAVED" : saveStatus === "fallback" ? "RECOVERY COPY" : "LOADING FILE"}</span><button className="icon-button" aria-label="Save career" onClick={saveNow}><Save size={17} /></button><button className="icon-button" aria-label="Load career" onClick={loadNow}><RefreshCw size={17} /></button><button className="icon-button" aria-label="Reset career" onClick={resetGame}><Menu size={21} /></button></div></header><main className="main-content"><div className={`active-mode-banner ${mode}`}><span>{mode === "player" ? "PLAYER CAREER" : "FRONT OFFICE CAREER"}</span><button onClick={resetGame}>NEW CAREER</button></div>{mode === "player" ? <PlayerMode player={player} tab={playerTab} setTab={setPlayerTab} nextOpponent={nextOpponent} onSimulate={simulateGame} onTrain={train} onBuy={(cost, item) => { if (player.cash < cost) { setToast("Not enough cash for that move."); return; } setPlayer((current) => ({ ...current, cash: current.cash - cost, fans: current.fans + 18000 })); setToast(`${item} added to your lifestyle portfolio.`); }} /> : <ManagerMode name={managerName} philosophy={managerPhilosophy} focus={managerFocus} setFocus={setManagerFocus} state={managerState} tab={managerTab} setTab={setManagerTab} nextOpponent={nextOpponent} onAction={managerAction} onSimulate={simulateManagerGame} />}</main>{toast && <div className="toast"><span className="toast-dot" />{toast}</div>}{mode === "player" ? <nav className="bottom-nav" aria-label="Player career navigation">{playerNav.map(({ id, label, icon: Icon }) => <button key={id} className={playerTab === id ? "active" : ""} onClick={() => setPlayerTab(id)}><Icon size={20} /><span>{label}</span></button>)}</nav> : <nav className="bottom-nav manager-nav" aria-label="Manager career navigation">{managerNav.map(({ id, label, icon: Icon }) => <button key={id} className={managerTab === id ? "active manager" : ""} onClick={() => setManagerTab(id)}><Icon size={20} /><span>{label}</span></button>)}</nav>}</div>;
}

function opponentRows(win: boolean): BoxRow[] { return [{ role: "PG", name: "T. Brooks", min: 36, pts: win ? 24 : 29, reb: 4, ast: 9, stl: 2, blk: 0 }, { role: "SG", name: "C. Bell", min: 33, pts: 21, reb: 5, ast: 4, stl: 1, blk: 0 }, { role: "SF", name: "S. Yates", min: 31, pts: 18, reb: 7, ast: 3, stl: 1, blk: 1 }, { role: "PF", name: "D. Monroe", min: 29, pts: 16, reb: 10, ast: 2, stl: 0, blk: 1 }, { role: "C", name: "R. Cole", min: 27, pts: 12, reb: 12, ast: 1, stl: 0, blk: 2 }, { role: "PG", name: "M. Sloan", min: 18, pts: 9, reb: 2, ast: 4, stl: 1, blk: 0 }, { role: "SG", name: "J. Parks", min: 14, pts: 6, reb: 2, ast: 1, stl: 0, blk: 0 }, { role: "PF", name: "O. James", min: 12, pts: 4, reb: 4, ast: 1, stl: 0, blk: 0 }, { role: "C", name: "E. King", min: 9, pts: 2, reb: 3, ast: 0, stl: 0, blk: 0 }, { role: "SF", name: "N. Fox", min: 6, pts: 0, reb: 1, ast: 0, stl: 0, blk: 0 }]; }
function boxRows(star: string, points: number, win: boolean): BoxRow[] { return [{ role: "SG", name: star, min: 36, pts: points, reb: 6, ast: 8, stl: 2, blk: 0, starter: true }, { role: "PF", name: "J. Walsh", min: 33, pts: win ? 17 : 12, reb: 9, ast: 4, stl: 1, blk: 1 }, { role: "C", name: "Joel Vickers", min: 29, pts: 11, reb: 12, ast: 2, stl: 1, blk: 2 }, { role: "SF", name: "H. González", min: 31, pts: 14, reb: 5, ast: 5, stl: 2, blk: 0 }, { role: "PG", name: "K. Norton", min: 27, pts: 9, reb: 3, ast: 7, stl: 1, blk: 0 }, { role: "SG", name: "R. Dorsey", min: 18, pts: 7, reb: 2, ast: 2, stl: 0, blk: 0 }, { role: "PF", name: "M. Okafor", min: 15, pts: 5, reb: 4, ast: 1, stl: 0, blk: 1 }, { role: "C", name: "L. Garza", min: 11, pts: 3, reb: 3, ast: 0, stl: 0, blk: 0 }, { role: "SG", name: "T. Quinn", min: 8, pts: 2, reb: 1, ast: 1, stl: 0, blk: 0 }, { role: "PG", name: "D. Reed", min: 5, pts: 0, reb: 1, ast: 1, stl: 0, blk: 0 }]; }

function Shell({ title, description, onBack }: { title: string; description: string; onBack?: () => void }) { return <header className="page-heading">{onBack && <button className="back-button" onClick={onBack}><ChevronLeft size={16} /> BACK</button>}<div className="eyebrow orange">{title === "Choose Your Career" ? "NEW CAREER FILE" : "RIMLINE / CAREER COMMAND"}</div><h1>{title}</h1><p>{description}</p></header>; }
function StartScreen({ onChoose }: { onChoose: (mode: Mode) => void }) { return <div className="app-shell onboarding-shell"><header className="topbar"><div className="brand-lockup"><img className="brand-logo" src="/manus-storage/rimline-mark_489959e3.png" alt="" /><span>RIM<span>LINE</span></span></div><span className="offline-badge">OFFLINE READY</span></header><main className="main-content onboarding"><Shell title="Choose Your Career" description="One league. Two ways to leave your mark. Your mode defines the story." /><div className="career-choice-grid"><button className="career-choice player-choice" onClick={() => onChoose("player")}><span className="choice-number">01</span><Sparkles size={27} /><strong>PLAYER MODE</strong><p>Own every minute. Build a name, chase the next contract, and turn performances into a legacy.</p><span className="choice-cta">CREATE PLAYER <ChevronRight size={17} /></span></button><button className="career-choice manager-choice" onClick={() => onChoose("manager")}><span className="choice-number">02</span><LayoutDashboard size={27} /><strong>MANAGER MODE</strong><p>Run the front office. Shape the culture, set the game plan, and build a contender over time.</p><span className="choice-cta">CREATE MANAGER <ChevronRight size={17} /></span></button></div><div className="onboarding-note"><span className="annotation-mark">RULE</span><p>Your choice creates a dedicated career. Player and Manager saves never share a screen.</p></div></main></div>; }
function CreatePlayerScreen({ onBack, onCreate }: { onBack: () => void; onCreate: (name: string, position: string, archetype: string) => void }) { const [name, setName] = useState(""); const [position, setPosition] = useState("SG"); const [archetype, setArchetype] = useState("Pure Shooter"); return <div className="app-shell onboarding-shell"><header className="topbar"><div className="brand-lockup"><img className="brand-logo" src="/manus-storage/rimline-mark_489959e3.png" alt="" /><span>RIM<span>LINE</span></span></div><span className="offline-badge">PLAYER FILE / 01</span></header><main className="main-content onboarding"><Shell title="Create Player" description="Start at the edge of the rotation. Earn everything after." onBack={onBack} /><section className="creation-panel"><div className="creation-hero"><div className="creation-avatar"><Circle size={38} /></div><div><div className="eyebrow orange">ROOKIE DOSSIER</div><h2>{name.trim() || "YOUR NAME"}</h2><p>{position} • {archetype}</p></div></div><label>PLAYER NAME<input value={name} onChange={(event) => setName(event.target.value)} placeholder="Enter your name" maxLength={22} /></label><label>POSITION<div className="choice-pills">{["PG", "SG", "SF", "PF", "C"].map((item) => <button key={item} type="button" className={position === item ? "active" : ""} onClick={() => setPosition(item)}>{item}</button>)}</div></label><label>ARCHETYPE<div className="choice-pills wide">{["Pure Shooter", "Two-Way Wing", "Floor General"].map((item) => <button key={item} type="button" className={archetype === item ? "active" : ""} onClick={() => setArchetype(item)}>{item}</button>)}</div></label><button className="primary-cta" onClick={() => onCreate(name, position, archetype)}>SIGN PLAYER FILE <ChevronRight size={18} /></button></section></main></div>; }
function CreateManagerScreen({ onBack, onCreate }: { onBack: () => void; onCreate: (name: string, philosophy: string) => void }) { const [name, setName] = useState(""); const [philosophy, setPhilosophy] = useState("Player Development"); return <div className="app-shell onboarding-shell manager-onboarding"><header className="topbar"><div className="brand-lockup"><img className="brand-logo" src="/manus-storage/rimline-mark_489959e3.png" alt="" /><span>RIM<span>LINE</span></span></div><span className="offline-badge manager-badge">FRONT OFFICE / 01</span></header><main className="main-content onboarding"><Shell title="Create Manager" description="Set the standard. Every decision becomes part of the culture." onBack={onBack} /><section className="creation-panel manager-creation"><div className="creation-hero"><div className="creation-avatar manager-avatar"><BriefcaseBusiness size={35} /></div><div><div className="eyebrow teal-label">FRONT OFFICE DOSSIER</div><h2>{name.trim() || "YOUR NAME"}</h2><p>GENERAL MANAGER • BOSTON COMETS</p></div></div><label>MANAGER NAME<input value={name} onChange={(event) => setName(event.target.value)} placeholder="Enter your name" maxLength={22} /></label><label>TEAM PHILOSOPHY<div className="choice-pills wide">{["Player Development", "Win Now", "Defense First"].map((item) => <button key={item} type="button" className={philosophy === item ? "active manager-pill" : ""} onClick={() => setPhilosophy(item)}>{item}</button>)}</div></label><div className="philosophy-note"><Shield size={18} /><span>Your philosophy influences staff actions, chemistry, and the pressure of every week.</span></div><button className="primary-cta manager-cta" onClick={() => onCreate(name, philosophy)}>OPEN FRONT OFFICE <ChevronRight size={18} /></button></section></main></div>; }

function WeeklyEventScreen({ event, week, season, onChoose }: { event: WeeklyEvent; week: number; season: number; onChoose: (choiceId: string) => void }) { return <div className={`app-shell event-shell ${event.mode}`}><header className="topbar"><div className="brand-lockup"><img className="brand-logo" src="/manus-storage/rimline-mark_489959e3.png" alt="" /><span>RIM<span>LINE</span></span></div><span className="offline-badge">SEASON {season} / WEEK {week}</span></header><main className="main-content event-main"><div className="event-kicker"><span className="annotation-mark">WEEKLY EVENT</span><span>{event.kicker}</span></div><h1>{event.title}</h1><p className="event-body">{event.body}</p><div className="event-source">{event.source}</div><div className="event-options">{event.options.map((option, index) => <button key={option.id} className="event-option" onClick={() => onChoose(option.id)}><span className="choice-number">0{index + 1}</span><strong>{option.label}</strong><small>{option.detail}</small><ChevronRight size={17} /></button>)}</div><div className="event-footnote"><span className="annotation-mark">NOTE</span><span>Weekly decisions are permanent. Consequences carry into the next game.</span></div></main></div>; }
function OffseasonScreen({ summary, onChoose }: { summary: SeasonSummary; onChoose: (choiceId: string) => void }) { const playerChoices = [{ id: "rest", label: "Recover & reset", detail: "+energy • +cash buffer" }, { id: "skill-camp", label: "Enter skill camp", detail: "+2 overall • +form" }, { id: "negotiate", label: "Push the contract", detail: "+cash • higher expectations" }]; const managerChoices = [{ id: "development-summit", label: "Development summit", detail: "+chemistry • +development" }, { id: "roster-audit", label: "Roster audit", detail: "+scouting • sharper depth chart" }, { id: "defensive-blueprint", label: "Defensive blueprint", detail: "+defense • identity first" }]; const choices = summary.mode === "player" ? playerChoices : managerChoices; return <div className={`app-shell offseason-shell ${summary.mode}`}><header className="topbar"><div className="brand-lockup"><img className="brand-logo" src="/manus-storage/rimline-mark_489959e3.png" alt="" /><span>RIM<span>LINE</span></span></div><span className="offline-badge">SEASON {summary.season} CLOSED</span></header><main className="main-content offseason-main"><div className="eyebrow orange">OFFSEASON / FILE CLOSED</div><h1>TURN THE PAGE</h1><p>The season is over. Your next standard starts with the decision below.</p><section className="season-summary"><span className="ledger-label">FINAL LEDGER</span><strong>{summary.record}</strong><small>{summary.highlight}</small><em>{summary.reward}</em></section><div className="event-options offseason-options">{choices.map((choice, index) => <button key={choice.id} className="event-option" onClick={() => onChoose(choice.id)}><span className="choice-number">0{index + 1}</span><strong>{choice.label}</strong><small>{choice.detail}</small><ChevronRight size={17} /></button>)}</div></main></div>; }
function PlayerMode({ player, tab, setTab, nextOpponent, onSimulate, onTrain, onBuy }: { player: Player; tab: PlayerTab; setTab: (tab: PlayerTab) => void; nextOpponent: Team; onSimulate: () => void; onTrain: (type: string) => void; onBuy: (cost: number, item: string) => void }) { return <>{tab === "home" && <PlayerHome player={player} nextOpponent={nextOpponent} onSimulate={onSimulate} />}{tab === "league" && <LeagueView />}{tab === "training" && <TrainingView player={player} onTrain={onTrain} />}{tab === "life" && <LifeView player={player} onBuy={onBuy} />}{tab === "stats" && <StatsView player={player} />}</>; }
function PlayerHome({ player, nextOpponent, onSimulate }: { player: Player; nextOpponent: Team; onSimulate: () => void }) { return <div className="screen home-screen"><div className="hero-card"><div className="player-copy"><div className="eyebrow orange"><span className="annotation-mark">01</span> MY PLAYER / CAREER FILE</div><h1>{player.name}</h1><p>{player.position} <span>/</span> {player.archetype} <span>/</span> USA <span>/</span> AGE 22</p><div className="team-line"><span className="mini-dot" /> Boston Comets <em>• {money(player.cash)} salary</em></div></div><div className="overall"><strong>{player.overall}</strong><span>OVR</span></div><div className="player-silhouette"><div className="portrait-glow" /><img className="portrait-image" src="/manus-storage/rimline-player-malik_e95d0f53.png" alt="" /></div></div><div className="energy-row"><div><div className="section-label"><span className="annotation-mark">04</span> ENERGY RESERVE</div><strong>{player.energy}%</strong></div><div className="progress"><span style={{ width: `${player.energy}%` }} /></div></div><section className="data-panel performance-panel"><div className="section-label"><span className="annotation-mark">02</span> SEASON VERDICT <span className="info-dot">i</span></div><div className="metric-grid"><Metric value={player.ppg.toFixed(1)} label="PPG" /><Metric value={player.rpg.toFixed(1)} label="RPG" /><Metric value={player.apg.toFixed(1)} label="APG" /></div></section><section className="data-panel news-panel"><div className="section-label">CAREER PULSE <span className="info-dot">i</span></div><div className="news-row"><div className="news-icon"><Flame size={18} /></div><div><strong>VERDICT: {player.wins}-{player.losses} through {player.game - 1} games</strong><small>FORM CHECK / NEXT WEEK LOADED</small></div></div></section><section className="next-game"><div className="section-label"><span className="annotation-mark">03</span> NEXT DECISION / GAME {player.game} OF 82 <span className="info-dot">i</span></div><div className="matchup"><div className="team"><div className="crest comet"><img src="/manus-storage/rimline-comets-crest_2d4a2f65.png" alt="" /></div><strong>Boston</strong><small>{player.wins}-{player.losses}</small></div><div className="vs"><span>4 DAYS AWAY</span><b>VS</b><small>AWAY</small></div><div className="team"><div className="crest pulse"><img src="/manus-storage/rimline-pulse-crest_cd5690fb.png" alt="" /></div><strong>{nextOpponent.name.split(" ")[0]}</strong><small>{nextOpponent.wins}-{nextOpponent.losses}</small></div></div><button className="primary-cta" onClick={onSimulate}><Play size={17} fill="currentColor" /> SIMULATE GAME <ChevronRight size={18} /></button></section></div>; }
function Metric({ value, label }: { value: string; label: string }) { return <div className="metric"><strong>{value}</strong><span>{label}</span></div>; }
function PageHeader({ title, description }: { title: string; description?: string }) { return <div className="page-heading"><h1>{title}</h1>{description && <p>{description}</p>}</div>; }
function LeagueView() { return <div className="screen"><PageHeader title="League" description="Every game changes the shape of the standings." /><div className="segmented"><button className="active">Teams</button><button>Players</button><button>Playoffs</button></div><div className="segmented conference"><button className="active">Eastern</button><button>Western</button></div><section className="standings"><div className="table-head"><span>TEAM</span><span>OVR</span><span>W</span><span>L</span></div>{teams.map((team) => <div className="standing-row" key={team.name}><span className="rank">{team.rank}</span><span className="team-cell"><span className="team-crest" style={{ borderColor: team.tone, color: team.tone }}>{team.city.slice(0, 1)}</span><strong>{team.name}</strong></span><strong>{team.overall}</strong><strong className="win">{team.wins}</strong><strong className="loss">{team.losses}</strong></div>)}</section></div>; }
function TrainingView({ player, onTrain }: { player: Player; onTrain: (type: string) => void }) { const options = [{ title: "Shooting Lab", detail: "+3PT / +FORM", icon: Circle }, { title: "Film Study", detail: "+IQ / +VISION", icon: LineChart }, { title: "Strength Room", detail: "+POWER / +STAMINA", icon: Dumbbell }]; return <div className="screen"><PageHeader title="Training" description="Spend energy now to shape the player you become." /><div className="training-meter"><div><span className="section-label">AVAILABLE ENERGY</span><strong>{player.energy}/100</strong></div><div className="progress"><span style={{ width: `${player.energy}%` }} /></div></div><div className="training-list">{options.map(({ title, detail, icon: Icon }) => <button className="training-row" key={title} onClick={() => onTrain(title)}><span className="training-icon"><Icon size={21} /></span><span><strong>{title}</strong><small>{detail}</small></span><ChevronRight size={18} /></button>)}</div><div className="quote">“The work shows up when the week gets loud.”<small>— Coach Rivera</small></div></div>; }
function LifeView({ player, onBuy }: { player: Player; onBuy: (cost: number, item: string) => void }) { const items = [{ name: "Kaze Shadow 400", cost: 35000, detail: "LIGHTWEIGHT • AGILE", icon: "◒" }, { name: "Northstar Coupe", cost: 85000, detail: "PERFORMANCE • LUXURY", icon: "▰" }, { name: "Harbor Loft", cost: 180000, detail: "RECOVERY • STATUS", icon: "⌂" }]; return <div className="screen"><PageHeader title="Life" description="Your career has a life beyond the box score." /><section className="social-panel"><div className="social-title"><span className="social-icon"><Sparkles size={16} /></span><strong>CHIRPER</strong><span className="verified">✓</span></div><div className="social-metrics"><Metric value={shortFans(player.fans)} label="FOLLOWERS" /><Metric value={money(player.cash)} label="CASH" /><Metric value="72" label="BRAND HEAT" /></div></section><div className="segmented"><button>Feed</button><button className="active">Shop</button><button>Brands</button></div><div className="section-label shop-label">VEHICLES & ESTATES</div><div className="shop-list">{items.map((item) => <div className="shop-row" key={item.name}><div className="shop-illustration">{item.icon}</div><div className="shop-copy"><strong>{item.name}</strong><small>{item.detail}</small><em>{money(item.cost)}</em></div><button className="outline-cta" onClick={() => onBuy(item.cost, item.name)}>BUY</button></div>)}</div></div>; }
function StatsView({ player }: { player: Player }) { const seasons = [["30/31", player.ppg.toFixed(1), player.apg.toFixed(1), player.rpg.toFixed(1)], ["29/30", "17.8", "3.3", "3.1"], ["28/29", "14.2", "2.7", "2.6"], ["27/28", "11.9", "2.4", "2.5"]]; return <div className="screen"><PageHeader title="Stats" description="The record of every version of your game." /><div className="profile-strip"><div className="profile-rating"><strong>{player.overall}</strong><small>OVR</small></div><div><div className="eyebrow orange">CAREER LEDGER</div><h2>{player.name}</h2><p>{player.archetype} • Boston Comets • Age 22</p></div></div><section className="stats-table"><div className="table-head"><span>YEAR</span><span>PPG</span><span>APG</span><span>RPG</span></div>{seasons.map((row) => <div className="stat-row" key={row[0]}><strong>{row[0]}</strong><strong>{row[1]}</strong><strong>{row[2]}</strong><strong>{row[3]}</strong></div>)}</section><div className="awards-line"><Medal size={19} /><div><strong>AWARDS TRACKER</strong><small>1× Rising Star shortlist • 3× Player of the Game</small></div></div></div>; }

function ManagerMode({ name, philosophy, focus, setFocus, state, tab, setTab, nextOpponent, onAction, onSimulate }: { name: string; philosophy: string; focus: string; setFocus: (value: string) => void; state: { chemistry: number; morale: number; defense: number; scouting: number; teamWins: number; teamLosses: number }; tab: ManagerTab; setTab: (tab: ManagerTab) => void; nextOpponent: Team; onAction: (action: string) => void; onSimulate: () => void }) { return <>{tab === "office" && <ManagerOffice name={name} philosophy={philosophy} focus={focus} setFocus={setFocus} state={state} nextOpponent={nextOpponent} onAction={onAction} onSimulate={onSimulate} />}{tab === "roster" && <ManagerRoster />}{tab === "league" && <LeagueView />}</>; }
function ManagerOffice({ name, philosophy, focus, setFocus, state, nextOpponent, onAction, onSimulate }: { name: string; philosophy: string; focus: string; setFocus: (value: string) => void; state: { chemistry: number; morale: number; defense: number; scouting: number; teamWins: number; teamLosses: number }; nextOpponent: Team; onAction: (action: string) => void; onSimulate: () => void }) { return <div className="screen manager-screen"><PageHeader title="Front Office" description={`GM ${name} • ${philosophy}. The team moves at your standard.`} /><section className="manager-hero"><div><div className="eyebrow teal-label">BOSTON COMETS</div><h2>FRONT OFFICE</h2><p>GENERAL MANAGER • HEAD COACH • CULTURE SETTER</p></div><div className="manager-record"><strong>{state.teamWins}-{state.teamLosses}</strong><small>SEASON RECORD</small></div></section><div className="manager-focus"><div className="section-label teal-label">GAME PLAN FOCUS</div><div className="focus-grid">{["Balanced", "Run & Gun", "Lockdown"].map((item) => <button key={item} className={focus === item ? "active" : ""} onClick={() => setFocus(item)}>{item}</button>)}</div></div><section className="manager-grid"><ManagerMetric label="CHEMISTRY" value={state.chemistry} tone="orange" /><ManagerMetric label="MORALE" value={state.morale} tone="gold" /><ManagerMetric label="DEFENSE" value={state.defense} tone="teal" /><ManagerMetric label="SCOUTING" value={state.scouting} tone="purple" /></section><div className="manager-actions"><div className="section-label teal-label">STAFF ACTIONS</div><button onClick={() => onAction("chemistry")}><Users size={18} /><span><strong>Run team session</strong><small>Improve chemistry before the week turns</small></span><ChevronRight size={17} /></button><button onClick={() => onAction("defense")}><Shield size={18} /><span><strong>Install defensive package</strong><small>Raise the floor against {nextOpponent.name}</small></span><ChevronRight size={17} /></button><button onClick={() => onAction("scouting")}><BriefcaseBusiness size={18} /><span><strong>Scout next opponent</strong><small>{nextOpponent.name} • {nextOpponent.overall} OVR</small></span><ChevronRight size={17} /></button></div><section className="next-game manager-next"><div className="section-label teal-label"><span className="annotation-mark manager-mark">01</span> NEXT WEEK / DECISION REQUIRED</div><div className="manager-next-copy"><div><strong>Boston Comets</strong><small>HOME / {state.teamWins}-{state.teamLosses}</small></div><div className="vs"><span>UP NEXT</span><b>VS</b><small>{nextOpponent.city}</small></div><div><strong>{nextOpponent.name}</strong><small>AWAY / {nextOpponent.wins}-{nextOpponent.losses}</small></div></div><button className="primary-cta manager-cta" onClick={onSimulate}><Play size={17} fill="currentColor" /> SIMULATE TEAM GAME <ChevronRight size={18} /></button></section></div>; }
function ManagerRoster() { const roster = [["PG", "D. Reed", 78, "Floor General"], ["SG", "A. Holloway", 82, "Two-Way Guard"], ["SF", "J. Walsh", 80, "Point Wing"], ["PF", "M. Okafor", 79, "Rim Runner"], ["C", "Joel Vickers", 83, "Anchor"]]; return <div className="screen"><PageHeader title="Roster Room" description="Know the people behind the plan. Roles become identity." /><section className="roster-table"><div className="roster-head"><span>POS</span><span>PLAYER</span><span>OVR</span></div>{roster.map(([pos, name, overall, role]) => <div className="roster-row" key={name}><span className="position-tag">{pos}</span><div><strong>{name}</strong><small>{role}</small></div><strong className="roster-ovr">{overall}</strong></div>)}</section><div className="manager-callout"><div className="section-label teal-label">FRONT OFFICE READ</div><p>The starting five are stable. Your next edge comes from development, not disruption.</p></div></div>; }
function TeamBoxTable({ team, rows, active }: { team: string; rows: BoxRow[]; active: boolean }) { return <div className="team-box"><div className={`boxscore-team-label ${active ? "active" : ""}`}>{team}<span>{active ? "HOME" : "AWAY"}</span></div><div className="boxscore-table-head"><span>PLAYER</span><span>MIN</span><span>PTS</span><span>REB</span><span>AST</span><span>STL</span><span>BLK</span></div>{rows.map((row) => <div className="boxscore-row" key={`${team}-${row.name}`}><span><small>{row.role}</small><strong>{row.name}</strong></span><strong>{row.min}</strong><strong>{row.pts}</strong><strong>{row.reb}</strong><strong>{row.ast}</strong><strong>{row.stl}</strong><strong>{row.blk}</strong></div>)}</div>; }
function ManagerMetric({ label, value, tone }: { label: string; value: number; tone: string }) { return <div className={`manager-metric ${tone}`}><div><span>{label}</span><strong>{value}</strong></div><div className="mini-progress"><i style={{ width: `${value}%` }} /></div></div>; }

function BoxScoreScreen({ box, onContinue }: { box: BoxScore; onContinue: () => void }) { const homeFirst = box.home === "Boston Comets"; return <div className="app-shell boxscore-shell"><header className="topbar"><div className="brand-lockup"><img className="brand-logo" src="/manus-storage/rimline-mark_489959e3.png" alt="" /><span>RIM<span>LINE</span></span></div><span className="offline-badge">WEEK {box.week} / FINAL</span></header><main className="main-content boxscore-main"><div className="boxscore-heading"><div className="eyebrow orange">GAME COMPLETE / {box.mode === "player" ? "PLAYER FILE" : "TEAM FILE"}</div><div className="scoreline"><div><strong>{box.homeScore}</strong><span>{box.home}</span></div><b>:</b><div><strong>{box.awayScore}</strong><span>{box.away}</span></div></div><div className="result-stamp">{box.winner} TAKE THE NIGHT</div></div><section className="boxscore-panel"><TeamBoxTable team={box.home} rows={box.homeRows} active={homeFirst} /><TeamBoxTable team={box.away} rows={box.awayRows} active={!homeFirst} /></section><div className="boxscore-note"><span className="annotation-mark">LOG</span><p>Every player accounted for. Review the full game before the week advances.</p></div><button className="primary-cta" onClick={onContinue}>CONTINUE TO NEXT WEEK <ChevronRight size={18} /></button></main></div>; }
