/* RIMLINE Tactical Courtbook — persisted command desk for reactive Player and Manager systems. */
import { useState } from "react";
import { Activity, BarChart3, BatteryCharging, BriefcaseBusiness, Dumbbell, Handshake, HeartPulse, Languages, Megaphone, Mic2, Settings2, Shield, Sparkles, Target, Trophy, Users, WalletCards, Waves } from "lucide-react";
import { applyDepthAction, type DepthAction, type DepthState } from "@/lib/depthSimulation";

type Mode = "player" | "manager";
type DeskTab = "work" | "story" | "market" | "world" | "settings";

const playerDrills: { action: DepthAction; name: string; detail: string; effect: string }[] = [
  { action: "shot-lab", name: "Shot Map Lab", detail: "Corner volume + pull-up balance", effect: "+2 CATCH & SHOOT • +1 PULL-UP • -8 ENERGY" },
  { action: "finishing", name: "Pressure Finishing", detail: "Contact reads at the rim", effect: "+2 RIM FINISH • +8 FATIGUE • -10 ENERGY" },
  { action: "film-room", name: "Film Room", detail: "Read the second defender", effect: "+3 TRUST • +0.4 CLUTCH NET • -4 ENERGY" },
  { action: "defense-drill", name: "Defensive Slide Work", detail: "Contain the first action", effect: "+0.3 DEFLECTIONS • +2 TRUST • -9 ENERGY" },
];
const managerMoves: { action: DepthAction; name: string; detail: string; effect: string }[] = [
  { action: "hold-assets", name: "Hold the line", detail: "Protect chemistry while leverage builds", effect: "+4 CHEMISTRY • +1 MARKET LEVERAGE" },
  { action: "trade-veteran", name: "Call the trade desk", detail: "Shop a veteran for a younger fit", effect: "+$9M CAP • +1 TRADE • -4 CHEMISTRY" },
  { action: "run-workouts", name: "Run prospect workouts", detail: "Turn scouting into a draft conviction", effect: "+8 TOP FIT CONFIDENCE" },
  { action: "hire-performance", name: "Upgrade performance staff", detail: "Invest in recovery and workload monitoring", effect: "+1 STAFF LEVEL • 10-MAN ROTATION" },
];

function Meter({ label, value, tone = "orange", invert = false }: { label: string; value: number; tone?: string; invert?: boolean }) {
  const visual = invert ? 100 - value : value;
  return <div className="depth-meter"><div><span>{label}</span><strong>{typeof value === "number" && !Number.isInteger(value) ? value.toFixed(1) : value}</strong></div><i><b className={tone} style={{ width: `${Math.max(0, Math.min(100, visual))}%` }} /></i></div>;
}

function ActionButton({ action, label, detail, icon = <Sparkles size={16} />, onAction }: { action: DepthAction; label: string; detail: string; icon?: React.ReactNode; onAction: (action: DepthAction, label: string) => void }) {
  return <button className="depth-action" onClick={() => onAction(action, label)}><span className="depth-number">↳</span><span><strong>{label}</strong><small>{detail}</small></span>{icon}</button>;
}

function DepthHeader({ mode, tab, setTab }: { mode: Mode; tab: DeskTab; setTab: (tab: DeskTab) => void }) {
  const tabs: { id: DeskTab; label: string }[] = mode === "player" ? [{ id: "work", label: "Work" }, { id: "story", label: "Story" }, { id: "market", label: "Market" }, { id: "world", label: "Legacy" }, { id: "settings", label: "Setup" }] : [{ id: "work", label: "Ops" }, { id: "story", label: "Culture" }, { id: "market", label: "Market" }, { id: "world", label: "Franchise" }, { id: "settings", label: "Setup" }];
  return <><div className="feature-heading"><div className="eyebrow orange">{mode === "player" ? "PLAYER COMMAND DESK" : "FRONT OFFICE COMMAND DESK"}</div><h1>{mode === "player" ? "OWN THE WEEK" : "RUN THE ERA"}</h1><p>{mode === "player" ? "The box score is only one report. Shape the work, the story, and the career around it." : "Every lever has a cost. Build an organization that can survive more than one hot month."}</p></div><div className="depth-tabs" role="tablist" aria-label="Command Desk sections">{tabs.map((item) => <button key={item.id} className={tab === item.id ? "active" : ""} onClick={() => setTab(item.id)} role="tab" aria-selected={tab === item.id}>{item.label}</button>)}</div></>;
}

export default function DepthPanel({ mode, playerName, team, state, onAction, onToast }: { mode: Mode; playerName?: string; team?: string; state: DepthState; onAction: (action: DepthAction) => void; onToast?: (message: string) => void }) {
  const [tab, setTab] = useState<DeskTab>("work");
  const player = playerName || "Your player";
  const run = (action: DepthAction, label: string) => { onAction(action); onToast?.(`${label} logged. ${state.lastAction}`); };
  const injuryMessage = state.injury.status === "Healthy" ? "Cleared for full workload" : `${state.injury.diagnosis} • ${state.injury.weeks} weeks`;

  return <div className={`screen depth-screen ${mode} ${state.largeType ? "large-type" : ""} ${state.colorBlind ? "colorblind-mode" : ""} ${state.reducedMotion ? "reduced-motion" : ""}`}><DepthHeader mode={mode} tab={tab} setTab={setTab} />
    {mode === "player" && tab === "work" && <><section className="depth-hero-strip"><div><span className="eyebrow orange">{player.toUpperCase()}</span><strong>THE NEXT VERSION IS TRAINED</strong><small>{team || "Boston Celtics"} • WORK WEEK • {state.difficulty.toUpperCase()} MODE</small></div><div className="depth-icon orange-icon"><Dumbbell size={22} /></div></section><div className="depth-meters"><Meter label="ENERGY" value={state.energy} /><Meter label="COACH TRUST" value={state.trust} tone="teal" /><Meter label="FATIGUE" value={state.fatigue} tone="gold" invert /></div><div className="depth-section-label"><span>01</span> PRACTICE MENU <small>RISK / RETURN</small></div><div className="depth-action-list">{playerDrills.map((item, index) => <button className="depth-action" key={item.name} onClick={() => run(item.action, item.name)}><span className="depth-number">0{index + 1}</span><span><strong>{item.name}</strong><small>{item.detail}</small><em>{item.effect}</em></span><Dumbbell size={16} /></button>)}</div><section className="depth-analytics"><div className="depth-section-label"><span>02</span> LIVE PERFORMANCE LAB <small>LAST {state.shotProfile.last10} GAMES</small></div><div className="analytics-grid"><div><strong>{state.shotProfile.rim}%</strong><span>RIM FINISH</span></div><div><strong>{state.shotProfile.catchShoot}%</strong><span>CATCH & SHOOT</span></div><div><strong>{state.shotProfile.clutchNet > 0 ? "+" : ""}{state.shotProfile.clutchNet.toFixed(1)}</strong><span>CLUTCH NET</span></div><div><strong>{state.shotProfile.deflections.toFixed(1)}</strong><span>DEFLECTIONS</span></div></div><div className="profile-bars"><div><span>RIM</span><i><b style={{ width: `${state.shotProfile.rim}%` }} /></i></div><div><span>CATCH</span><i><b style={{ width: `${state.shotProfile.catchShoot}%` }} /></i></div><div><span>PULL-UP</span><i><b style={{ width: `${state.shotProfile.pullUp}%` }} /></i></div></div></section><section className="depth-callout"><HeartPulse size={18} /><div><strong>{state.injury.status.toUpperCase()} / {injuryMessage}</strong><small>Rehab readiness {state.injury.rehab}% • medical staff protects availability.</small></div><button onClick={() => run("rehab", "Rehab block")}>REHAB</button></section></>}
    {mode === "player" && tab === "story" && <><div className="depth-story-card"><span className="annotation-mark">MEDIA / WEEKLY CHOICE</span><h2>The story travels with you</h2><p>A teammate wants a larger voice in the offense while the league feed is asking for a quote. Pick the signal you want to send.</p><div className="depth-choice-grid"><button onClick={() => run("media-team", "Give the team credit")}><span>01</span><strong>Give the team credit</strong></button><button onClick={() => run("media-touches", "Call for more touches")}><span>02</span><strong>Call for more touches</strong></button><button onClick={() => run("media-quiet", "Keep it short")}><span>03</span><strong>Keep it short</strong></button></div></div><div className="depth-section-label"><span>02</span> RELATIONSHIP NETWORK <small>TRUST IS A STAT</small></div><div className="relationship-grid"><div><Users size={17} /><strong>{state.relationships.teammate}</strong><span>TEAMMATE</span></div><div><Mic2 size={17} /><strong>{state.reputation}</strong><span>PUBLIC REP</span></div><div><Activity size={17} /><strong>{state.relationships.mentor}</strong><span>MENTOR</span></div></div><div className="depth-action-list"><ActionButton action="relationship-listen" label="Listen first" detail="Give the teammate the next possession" icon={<Users size={16} />} onAction={run} /><ActionButton action="relationship-compete" label="Compete for the role" detail="Raise rival heat without losing the room" icon={<Target size={16} />} onAction={run} /><ActionButton action="relationship-workout" label="Create a shared workout" detail="Mentor the next class" icon={<Dumbbell size={16} />} onAction={run} /></div></>}
    {mode === "player" && tab === "market" && <><div className="depth-market-grid"><section className="depth-card"><Handshake size={19} /><span>AGENT / CONTRACT DESK</span><strong>${state.contract.aav.toFixed(1)}M AAV • {state.contract.years} YRS</strong><p>{state.contract.guaranteed ? "Guaranteed structure" : "Non-guaranteed structure"} • incentives: {state.contract.incentives.join(" / ")}</p><button onClick={() => run("negotiate-contract", "Contract negotiation")}>NEGOTIATE TERMS</button></section><section className="depth-card"><Megaphone size={19} /><span>ENDORSEMENT DESK</span><strong>${state.contract.endorsementValue}K campaign value</strong><p>Media days trade recovery time for brand heat and future leverage.</p><button onClick={() => run("accept-endorsement", "Endorsement decision")}>ACCEPT CAMPAIGN</button></section></div><div className="depth-section-label"><span>03</span> MARKET POSITION <small>LEVERAGE / FIT / RUNWAY</small></div><div className="contract-read"><div><strong>{state.trust}</strong><span>LEVERAGE</span></div><div><strong>{state.contract.years} YRS</strong><span>CONTROL</span></div><div><strong>{state.reputation}%</strong><span>BRAND HEAT</span></div></div></>}
    {mode === "player" && tab === "world" && <><div className="legacy-rail"><div className="legacy-score"><Trophy size={19} /><strong>{state.history.length}</strong><span>ERA LOGS</span></div><div><span className="eyebrow orange">AWARD RACE / CAREER HISTORY</span><strong>{state.awards[0].progress}% toward {state.awards[0].name}</strong><small>Milestones, award races, Hall of Fame status, and post-career paths are tracked in the local timeline.</small></div></div><div className="analytics-grid award-grid">{state.awards.map((award) => <div key={award.name}><strong>{award.progress}%</strong><span>{award.name}</span><small>{award.status}</small></div>)}</div><div className="post-career-grid"><button onClick={() => run("relationship-workout", "Mentor path")}><Sparkles size={18} /><strong>MENTOR</strong><span>Shape the next class</span></button><button onClick={() => run("media-team", "Broadcast path")}><Mic2 size={18} /><strong>BROADCAST</strong><span>Turn insight into a second act</span></button><button onClick={() => run("negotiate-contract", "Executive path")}><BriefcaseBusiness size={18} /><strong>EXECUTIVE</strong><span>Build the next roster</span></button></div><div className="history-strip">{state.history.slice(-5).map((item) => <span key={item}>• {item}</span>)}</div></>}
    {mode === "manager" && tab === "work" && <><section className="depth-hero-strip manager-strip"><div><span className="eyebrow teal-label">BOSTON CELTICS / OPERATIONS</span><strong>EVERY DETAIL COMPOUNDS</strong><small>Run systems, protect the room, and make the next move early.</small></div><div className="depth-icon teal-icon"><BriefcaseBusiness size={22} /></div></section><div className="depth-meters"><Meter label="CHEMISTRY" value={state.chemistry} /><Meter label="HEALTH" value={state.fatigue} tone="teal" invert /><Meter label="SCOUTING" value={state.rookieClass[0].confidence} tone="gold" /></div><div className="depth-section-label"><span>01</span> OPERATING BOARD <small>DECISIONS WITH COST</small></div><div className="depth-action-list">{managerMoves.map((item, index) => <button className="depth-action" key={item.name} onClick={() => run(item.action, item.name)}><span className="depth-number">0{index + 1}</span><span><strong>{item.name}</strong><small>{item.detail}</small><em>{item.effect}</em></span><BriefcaseBusiness size={16} /></button>)}</div><section className="depth-analytics"><div className="depth-section-label"><span>02</span> TEAM ANALYTICS <small>ROTATION READ</small></div><div className="analytics-grid"><div><strong>{state.tactics.rotationSize}</strong><span>ROTATION SIZE</span></div><div><strong>{state.tactics.system}</strong><span>SYSTEM</span></div><div><strong>{state.tactics.defense}</strong><span>DEF IDENTITY</span></div><div><strong>${state.transactions.capSpace}M</strong><span>CAP ROOM</span></div></div></section></>}
    {mode === "manager" && tab === "story" && <><div className="depth-story-card manager-story"><span className="annotation-mark">CULTURE / WEEKLY CHECK</span><h2>The room is watching</h2><p>A veteran wants clarity on their role while a rookie is earning louder reps. Your response sets the standard.</p><div className="depth-choice-grid"><button onClick={() => run("hold-assets", "Open the rotation")}><span>01</span><strong>Open the rotation</strong></button><button onClick={() => run("set-lockdown", "Protect the identity")}><span>02</span><strong>Protect the identity</strong></button><button onClick={() => run("relationship-listen", "Call a players-only meeting")}><span>03</span><strong>Players-only meeting</strong></button></div></div><div className="relationship-grid"><div><Users size={17} /><strong>{state.chemistry}</strong><span>TEAM CHEMISTRY</span></div><div><Shield size={17} /><strong>{state.tactics.defense}</strong><span>DEFENSE IDENTITY</span></div><div><Activity size={17} /><strong>{100 - state.fatigue}</strong><span>HEALTH INDEX</span></div></div></>}
    {mode === "manager" && tab === "market" && <><div className="depth-market-grid"><section className="depth-card"><WalletCards size={19} /><span>TRANSACTION DESK</span><strong>${state.transactions.capSpace}M available</strong><p>{state.transactions.pending[0] || "No pending frameworks"} • {state.transactions.trades} completed trades.</p><button onClick={() => run("trade-veteran", "Trade framework")}>OPEN TRADE MACHINE</button></section><section className="depth-card"><Trophy size={19} /><span>ROOKIE CLASS / SCOUTING</span><strong>{state.rookieClass[0].name} leads the board</strong><p>{state.rookieClass[0].school} • {state.rookieClass[0].position} • OVR {state.rookieClass[0].overall} • POT {state.rookieClass[0].potential}</p><button onClick={() => run("run-workouts", "Prospect workouts")}>RUN WORKOUTS</button></section></div><div className="depth-section-label"><span>03</span> STAFF LEDGER <small>HIRE THE EDGE</small></div><div className="staff-ledger">{state.staff.map((item) => <div key={item.role}><strong>LVL {item.level}</strong><span>{item.role.toUpperCase()}</span><small>{item.specialty}</small></div>)}</div><div className="rookie-list">{state.rookieClass.map((prospect) => <span key={prospect.name}>{prospect.name} / {prospect.school} / {prospect.confidence}% confidence</span>)}</div></>}
    {mode === "manager" && tab === "world" && <><div className="legacy-rail"><div className="legacy-score"><Trophy size={19} /><strong>{state.league.rivalryHeat}</strong><span>RIVALRY HEAT</span></div><div><span className="eyebrow teal-label">FRANCHISE IDENTITY</span><strong>{state.tactics.system} basketball is the organizational brief.</strong><small>{state.league.ruleChange} • expansion watch {state.league.expansionWatch}% • league timeline persists locally.</small></div></div><div className="franchise-grid"><div><strong>{state.tactics.system}</strong><span>PLAY STYLE</span></div><div><strong>{state.league.expansionWatch}%</strong><span>EXPANSION WATCH</span></div><div><strong>{state.league.rivalryHeat}</strong><span>RIVALRY HEAT</span></div></div><div className="history-strip">{state.league.timeline.map((item) => <span key={item}>• {item}</span>)}</div></>}
    {tab === "settings" && <><div className="depth-settings"><div className="settings-row"><div><strong>SIMULATION DIFFICULTY</strong><small>Current mode: {state.difficulty}. Higher difficulty increases variance.</small></div><button className="settings-chip" onClick={() => run("cycle-difficulty", "Difficulty cycle")}><Target size={15} /> {state.difficulty}</button></div><div className="settings-row"><div><strong>LARGE TYPE MODE</strong><small>Increase labels and reading size for the command desk.</small></div><button className={`toggle ${state.largeType ? "active" : ""}`} onClick={() => run("set-large-type", "Large type")}>{state.largeType ? "ON" : "OFF"}</button></div><div className="settings-row"><div><strong>COLOR-BLIND PALETTE</strong><small>Use shape and contrast as well as accent color.</small></div><button className={`toggle ${state.colorBlind ? "active" : ""}`} onClick={() => run("toggle-colorblind", "Color-blind palette")}>{state.colorBlind ? "ON" : "OFF"}</button></div><div className="settings-row"><div><strong>REDUCED MOTION</strong><small>Keep the courtbook calm on devices that prefer less motion.</small></div><button className={`toggle ${state.reducedMotion ? "active" : ""}`} onClick={() => run("toggle-motion", "Reduced motion")}>{state.reducedMotion ? "ON" : "OFF"}</button></div><div className="settings-row"><div><strong>LANGUAGE / LOCALIZATION</strong><small>Copy structure is ready for English, Spanish, and French.</small></div><button className="settings-chip" onClick={() => run("set-locale", "Language") }><Languages size={15} /> {state.locale}</button></div><div className="settings-row"><div><strong>OFFLINE SIMULATION</strong><small>Decisions, history, challenges, and settings save locally.</small></div><span className="settings-status"><BatteryCharging size={16} /> READY</span></div></div><div className="depth-callout"><Waves size={18} /><div><strong>{state.lastAction}</strong><small>{state.challenges.filter((item) => item.active).length} active challenge tracks • {state.history.length} local career logs.</small></div></div><div className="depth-section-label"><span>02</span> CHALLENGE BOARD <small>REPLAYABLE OBJECTIVES</small></div><div className="depth-action-list">{state.challenges.map((challenge) => <button className={`depth-action ${challenge.active ? "active-challenge" : ""}`} key={challenge.name} onClick={() => run(challenge.name === "Underdog Run" ? "challenge-underdog" : challenge.name === "Cap Discipline" ? "challenge-cap" : "challenge-rookie", challenge.name)}><span className="depth-number">{challenge.active ? "ON" : "OFF"}</span><span><strong>{challenge.name}</strong><small>{challenge.objective} • {challenge.progress} progress</small><em>{challenge.reward}</em></span><Target size={16} /></button>)}</div></>}
  </div>;
}
