/* RIMLINE Tactical Courtbook — Command Desk for deeper offline career decisions. */
import { useMemo, useState } from "react";
import { Activity, BarChart3, BatteryCharging, BriefcaseBusiness, Dumbbell, Handshake, Megaphone, Mic2, Settings2, Shield, Sparkles, Trophy, Users } from "lucide-react";

type Mode = "player" | "manager";
type DeskTab = "work" | "story" | "market" | "world" | "settings";

const playerDrills = [
  { name: "Shot Map Lab", detail: "Corner volume + pull-up balance", effect: "+2 SHOT • +1 FORM • -8 ENERGY" },
  { name: "Pressure Finishing", detail: "Contact reads at the rim", effect: "+2 ATH • +1 PPG • -10 ENERGY" },
  { name: "Film Room", detail: "Read the second defender", effect: "+2 IQ • +2 TRUST • -4 ENERGY" },
  { name: "Defensive Slide Work", detail: "Contain the first action", effect: "+2 DEF • +1 TRUST • -9 ENERGY" },
];
const playerStories = [
  { title: "Postgame podium", body: "A reporter asks whether your scoring can travel into the playoffs.", choices: ["Give the team credit", "Call for more touches", "Keep it short"] },
  { title: "Feed is moving", body: "Your last-minute assist is trending. Fans want a signature shoe moment.", choices: ["Lean into the story", "Redirect to the work", "Ask the agent to filter it"] },
  { title: "The circle check", body: "A teammate wants a larger voice in the offense before the next road swing.", choices: ["Listen first", "Compete for the role", "Create a shared workout"] },
];
const managerMoves = [
  { name: "Set the rotation", detail: "Lock a 9-man group around your identity", effect: "+4 CHEMISTRY • +2 FIT" },
  { name: "Upgrade performance staff", detail: "Invest in recovery and workload monitoring", effect: "+6 HEALTH • -8M CAP" },
  { name: "Call the trade desk", detail: "Shop a veteran for a younger fit", effect: "+1 FLEX • RISKY" },
  { name: "Run prospect workouts", detail: "Turn scouting into a draft conviction", effect: "+5 SCOUTING • +1 FIT" },
];

function Meter({ label, value, tone = "orange" }: { label: string; value: number; tone?: string }) {
  return <div className="depth-meter"><div><span>{label}</span><strong>{value}</strong></div><i><b className={tone} style={{ width: `${value}%` }} /></i></div>;
}

function DepthHeader({ mode, tab, setTab }: { mode: Mode; tab: DeskTab; setTab: (tab: DeskTab) => void }) {
  const tabs: { id: DeskTab; label: string }[] = mode === "player" ? [{ id: "work", label: "Work" }, { id: "story", label: "Story" }, { id: "market", label: "Market" }, { id: "world", label: "Legacy" }, { id: "settings", label: "Setup" }] : [{ id: "work", label: "Ops" }, { id: "story", label: "Culture" }, { id: "market", label: "Market" }, { id: "world", label: "Franchise" }, { id: "settings", label: "Setup" }];
  return <><div className="feature-heading"><div className="eyebrow orange">{mode === "player" ? "PLAYER COMMAND DESK" : "FRONT OFFICE COMMAND DESK"}</div><h1>{mode === "player" ? "OWN THE WEEK" : "RUN THE ERA"}</h1><p>{mode === "player" ? "The box score is only one report. Shape the work, the story, and the career around it." : "Every lever has a cost. Build an organization that can survive more than one hot month."}</p></div><div className="depth-tabs" role="tablist" aria-label="Command Desk sections">{tabs.map((item) => <button key={item.id} className={tab === item.id ? "active" : ""} onClick={() => setTab(item.id)} role="tab" aria-selected={tab === item.id}>{item.label}</button>)}</div></>;
}

export default function DepthPanel({ mode, playerName, team, onToast }: { mode: Mode; playerName?: string; team?: string; onToast?: (message: string) => void }) {
  const [tab, setTab] = useState<DeskTab>("work");
  const [energy, setEnergy] = useState(78);
  const [trust, setTrust] = useState(61);
  const [chemistry, setChemistry] = useState(72);
  const [fatigue, setFatigue] = useState(24);
  const [rep, setRep] = useState(51);
  const [result, setResult] = useState("No decision logged yet.");
  const [difficulty, setDifficulty] = useState("Standard");
  const [largeType, setLargeType] = useState(false);
  const player = playerName || "Your player";
  const currentStory = useMemo(() => playerStories[(trust + chemistry) % playerStories.length], [trust, chemistry]);

  const notify = (message: string) => { setResult(message); onToast?.(message); };
  const drill = (name: string, cost: number) => { if (energy < cost) return notify("Recovery first. Energy is below the drill threshold."); setEnergy((value) => Math.max(0, value - cost)); setTrust((value) => Math.min(99, value + 2)); setFatigue((value) => Math.min(99, value + Math.max(2, cost - 5))); notify(`${name} logged. The next game will read the work.`); };
  const managerMove = (name: string, cost: number) => { setChemistry((value) => Math.min(99, value + (name.includes("rotation") ? 4 : 2))); notify(`${name} moved into the front-office ledger.`); if (cost) notify(`${name} logged. ${cost}M cap flexibility committed.`); };

  return <div className={`screen depth-screen ${mode} ${largeType ? "large-type" : ""}`}><DepthHeader mode={mode} tab={tab} setTab={setTab} />
    {mode === "player" && tab === "work" && <><section className="depth-hero-strip"><div><span className="eyebrow orange">{player.toUpperCase()}</span><strong>THE NEXT VERSION IS TRAINED</strong><small>{team || "Boston Celtics"} • Week 28 • {difficulty.toUpperCase()} MODE</small></div><div className="depth-icon orange-icon"><Dumbbell size={22} /></div></section><div className="depth-meters"><Meter label="ENERGY" value={energy} /><Meter label="COACH TRUST" value={trust} tone="teal" /><Meter label="FATIGUE" value={fatigue} tone="gold" /></div><div className="depth-section-label"><span>01</span> PRACTICE MENU <small>RISK / RETURN</small></div><div className="depth-action-list">{playerDrills.map((item, index) => <button className="depth-action" key={item.name} onClick={() => drill(item.name, [8, 4, 4, 9][index])}><span className="depth-number">0{index + 1}</span><span><strong>{item.name}</strong><small>{item.detail}</small><em>{item.effect}</em></span><Dumbbell size={16} /></button>)}</div><section className="depth-analytics"><div className="depth-section-label"><span>02</span> SCOUTING REPORT <small>LAST 10 GAMES</small></div><div className="analytics-grid"><div><strong>54%</strong><span>RIM FINISH</span></div><div><strong>38%</strong><span>CATCH & SHOOT</span></div><div><strong>+4.8</strong><span>CLUTCH NET</span></div><div><strong>1.7</strong><span>DEFLECTIONS</span></div></div></section></>}
    {mode === "player" && tab === "story" && <><div className="depth-story-card"><span className="annotation-mark">MEDIA / {currentStory.title.toUpperCase()}</span><h2>{currentStory.title}</h2><p>{currentStory.body}</p><div className="depth-choice-grid">{currentStory.choices.map((choice, index) => <button key={choice} onClick={() => { setRep((value) => Math.min(99, value + (index === 0 ? 3 : 1))); setChemistry((value) => Math.min(99, value + (index === 2 ? 4 : 0))); notify(`${choice} chosen. Your reputation and relationships will carry it forward.`); }}><span>0{index + 1}</span><strong>{choice}</strong></button>)}</div></div><div className="depth-section-label"><span>02</span> THE CIRCLE <small>RELATIONSHIPS ARE LEVERAGE</small></div><div className="relationship-grid"><div><Users size={17} /><strong>72</strong><span>TEAM CHEMISTRY</span></div><div><Mic2 size={17} /><strong>{rep}</strong><span>PUBLIC REPUTATION</span></div><div><Activity size={17} /><strong>{trust}</strong><span>COACH TRUST</span></div></div></>}
    {mode === "player" && tab === "market" && <><div className="depth-market-grid"><section className="depth-card"><Handshake size={19} /><span>AGENT BRIEF</span><strong>Market leverage is rising.</strong><p>Keep the work visible and your next deal can ask for role, years, and incentives.</p><button onClick={() => notify("Agent brief updated: prioritize role security over headline dollars.")}>UPDATE BRIEF</button></section><section className="depth-card"><Megaphone size={19} /><span>ENDORSEMENT DESK</span><strong>Northstar wants a campaign.</strong><p>$48K guarantee • 2 media days • +brand heat • -recovery window</p><button onClick={() => notify("Endorsement accepted. Two media days added to the calendar.")}>REVIEW DEAL</button></section></div><div className="depth-section-label"><span>03</span> CONTRACT READ <small>LEVERAGE / FIT / RUNWAY</small></div><div className="contract-read"><div><strong>$16.2M</strong><span>PROJECTED AAV</span></div><div><strong>3 YRS</strong><span>TEAM CONTROL</span></div><div><strong>87%</strong><span>SYSTEM FIT</span></div></div></>}
    {mode === "player" && tab === "world" && <><div className="legacy-rail"><div className="legacy-score"><Trophy size={19} /><strong>18</strong><span>LEGACY</span></div><div><span className="eyebrow orange">RECORD WATCH</span><strong>7 assists from the franchise top 10</strong><small>Milestones unlock new story events, award weight, and post-career options.</small></div></div><div className="post-career-grid"><button onClick={() => notify("Mentor path queued: veteran players will ask for your film-room time.")}><Sparkles size={18} /><strong>MENTOR</strong><span>Shape the next class</span></button><button onClick={() => notify("Broadcast path queued: your media reputation is now a career asset.")}><Mic2 size={18} /><strong>BROADCAST</strong><span>Turn insight into a second act</span></button><button onClick={() => notify("Front-office path queued: ownership is tracking your leadership score.")}><BriefcaseBusiness size={18} /><strong>EXECUTIVE</strong><span>Build the next roster</span></button></div></>}
    {mode === "manager" && tab === "work" && <><section className="depth-hero-strip manager-strip"><div><span className="eyebrow teal-label">BOSTON CELTICS / OPERATIONS</span><strong>EVERY DETAIL COMPOUNDS</strong><small>Run systems, protect the room, and make the next move early.</small></div><div className="depth-icon teal-icon"><BriefcaseBusiness size={22} /></div></section><div className="depth-meters"><Meter label="CHEMISTRY" value={chemistry} /><Meter label="HEALTH" value={100 - fatigue} tone="teal" /><Meter label="SCOUTING" value={64} tone="gold" /></div><div className="depth-section-label"><span>01</span> OPERATING BOARD <small>DECISIONS WITH COST</small></div><div className="depth-action-list">{managerMoves.map((item, index) => <button className="depth-action" key={item.name} onClick={() => managerMove(item.name, index === 1 ? 8 : 0)}><span className="depth-number">0{index + 1}</span><span><strong>{item.name}</strong><small>{item.detail}</small><em>{item.effect}</em></span><BriefcaseBusiness size={16} /></button>)}</div><section className="depth-analytics"><div className="depth-section-label"><span>02</span> TEAM ANALYTICS <small>ROTATION READ</small></div><div className="analytics-grid"><div><strong>9</strong><span>ROTATION SIZE</span></div><div><strong>81</strong><span>AVG OVR</span></div><div><strong>+6.2</strong><span>BENCH NET</span></div><div><strong>14</strong><span>SCOUTED FITS</span></div></div></section></>}
    {mode === "manager" && tab === "story" && <><div className="depth-story-card manager-story"><span className="annotation-mark">CULTURE / WEEKLY CHECK</span><h2>The room is watching</h2><p>A veteran wants clarity on their role while a rookie is earning louder reps. Your response sets the standard.</p><div className="depth-choice-grid">{["Open the rotation", "Protect the veterans", "Call a players-only meeting"].map((choice, index) => <button key={choice} onClick={() => { setChemistry((value) => Math.min(99, value + (index === 2 ? 5 : 2))); notify(`${choice} chosen. Chemistry now reads ${chemistry + (index === 2 ? 5 : 2)}.`); }}><span>0{index + 1}</span><strong>{choice}</strong></button>)}</div></div><div className="relationship-grid"><div><Users size={17} /><strong>{chemistry}</strong><span>TEAM CHEMISTRY</span></div><div><Shield size={17} /><strong>78</strong><span>DEFENSE IDENTITY</span></div><div><Activity size={17} /><strong>{100 - fatigue}</strong><span>HEALTH INDEX</span></div></div></>}
    {mode === "manager" && tab === "market" && <><div className="depth-market-grid"><section className="depth-card"><Handshake size={19} /><span>TRANSACTION DESK</span><strong>Three teams called.</strong><p>Explore a veteran-for-prospect deal or hold the line and protect chemistry.</p><button onClick={() => notify("Trade machine opened: asset values are now visible in the Moves tab.")}>OPEN TRADE MACHINE</button></section><section className="depth-card"><Trophy size={19} /><span>DRAFT BOARD</span><strong>Fit over fame.</strong><p>Three prospects cleared the first screen. Workouts can change the order.</p><button onClick={() => notify("Prospect workout scheduled. Scouting confidence increased.")}>RUN WORKOUTS</button></section></div><div className="depth-section-label"><span>03</span> STAFF LEDGER <small>HIRE THE EDGE</small></div><div className="staff-ledger"><div><strong>+6</strong><span>PERFORMANCE</span></div><div><strong>+4</strong><span>SCOUTING</span></div><div><strong>+8</strong><span>MEDICAL</span></div><div><strong>-$8M</strong><span>CAP COST</span></div></div></>}
    {mode === "manager" && tab === "world" && <><div className="legacy-rail"><div className="legacy-score"><Trophy size={19} /><strong>11</strong><span>ERA</span></div><div><span className="eyebrow teal-label">FRANCHISE IDENTITY</span><strong>Defense travels. Culture compounds.</strong><small>Boston's market pressure is high, but the system fit is cleaner when the room stays connected.</small></div></div><div className="franchise-grid"><div><strong>WIN NOW</strong><span>OWNER EXPECTATION</span></div><div><strong>83</strong><span>MARKET PRESSURE</span></div><div><strong>6</strong><span>RIVALS TRACKED</span></div></div></>}
    {tab === "settings" && <><div className="depth-settings"><div className="settings-row"><div><strong>SIMULATION DIFFICULTY</strong><small>Changes variance, injury risk, and market pressure.</small></div><select value={difficulty} onChange={(event) => { setDifficulty(event.target.value); notify(`Difficulty set to ${event.target.value}.`); }}><option>Standard</option><option>Competitive</option><option>Story Mode</option></select></div><div className="settings-row"><div><strong>LARGE TYPE MODE</strong><small>Increase labels and reading size for the command desk.</small></div><button className={`toggle ${largeType ? "active" : ""}`} onClick={() => setLargeType((value) => !value)} aria-pressed={largeType}>{largeType ? "ON" : "OFF"}</button></div><div className="settings-row"><div><strong>ACCESSIBILITY READOUT</strong><small>All meters and decisions remain available as text.</small></div><span className="settings-status"><Settings2 size={16} /> TEXT READY</span></div><div className="settings-row"><div><strong>OFFLINE SIMULATION</strong><small>Local decisions are available without a signal.</small></div><span className="settings-status"><BatteryCharging size={16} /> READY</span></div></div><div className="depth-callout"><Sparkles size={18} /><div><strong>{result}</strong><small>Every choice is logged locally before the next week turns.</small></div></div></>}
  </div>;
}
