/* RIMLINE Tactical Courtbook — expansion desk: dense evidence panels, local persistence, and mode-specific decision surfaces. */
import { useMemo, useState } from "react";
import { ArrowRightLeft, CalendarDays, Check, CircleDollarSign, Crown, Dices, Dumbbell, FileText, Flame, GitBranch, Medal, RotateCcw, Shield, Sparkles, Target, Trophy, Users, WandSparkles, X } from "lucide-react";

type Mode = "player" | "manager";
type RosterPlayer = { name: string; role: string; overall: number; morale: number };
type RookiePlayer = { name: string; school: string; role: string; overall: number; potential: number; fit: number };
type ExpansionState = { tab: string; seed: number; development: number; contractLeverage: number; tradeCount: number; rotationFocus: string; completed: string[]; lastDecision: string };

const initialExpansion: ExpansionState = { tab: "overview", seed: 4821, development: 3, contractLeverage: 66, tradeCount: 0, rotationFocus: "Balanced", completed: [], lastDecision: "No decisions logged this week." };
const teams = ["Boston Celtics", "Oklahoma City Thunder", "Cleveland Cavaliers", "Denver Nuggets", "New York Knicks", "Minnesota Timberwolves", "Los Angeles Lakers", "Phoenix Suns"];
const rookies = [
  { name: "Cameron Ellis", school: "Duke", role: "Two-Way Wing", overall: 74, potential: 91, fit: 88 },
  { name: "Malik Foster", school: "UConn", role: "Rim Protector", overall: 72, potential: 87, fit: 82 },
  { name: "Andre Bell", school: "Kansas", role: "Floor General", overall: 71, potential: 89, fit: 79 },
  { name: "Noah Whitaker", school: "UCLA", role: "Shot Creator", overall: 76, potential: 86, fit: 74 },
  { name: "Isaiah Cole", school: "Kentucky", role: "Stretch Big", overall: 70, potential: 85, fit: 91 },
];
const awards = [
  ["MVP", "Jayson Tatum", "24.8 PPG • 7.2 RPG • 6.9 APG"],
  ["DPOY", "Victor Wembanyama", "2.8 BPG • 10.6 RPG"],
  ["ROY", "Cooper Flagg", "18.1 PPG • 7.4 RPG"],
  ["6MOY", "Payton Pritchard", "15.2 PPG off the bench"],
];

function loadState(): ExpansionState { try { return { ...initialExpansion, ...(JSON.parse(localStorage.getItem("rimline-expansion-desk") || "{}") as Partial<ExpansionState>) }; } catch { return initialExpansion; } }
function clamp(value: number, min = 0, max = 99) { return Math.max(min, Math.min(max, value)); }
function scoreSeed(seed: number, index: number) { return ((seed * 17 + index * 31) % 97) + 1; }

export default function ExpansionDesk({ mode, playerName, team, playerOverall, playerWins, capSpace = 42, roster = [], rookieClass = [], fatigue = 24, trust = 61, injuryStatus = "Healthy", activeChallenge = "No active challenge", onToast }: { mode: Mode; playerName: string; team: string; playerOverall: number; playerWins: number; capSpace?: number; roster?: RosterPlayer[]; rookieClass?: RookiePlayer[]; fatigue?: number; trust?: number; injuryStatus?: string; activeChallenge?: string; onToast?: (message: string) => void }) {
  const [state, setState] = useState<ExpansionState>(() => loadState());
  const [tradeTarget, setTradeTarget] = useState("Jrue Holiday");
  const [tradeAsset, setTradeAsset] = useState("2028 first-round pick");
  const [tradeNotice, setTradeNotice] = useState("");
  const [selectedRookie, setSelectedRookie] = useState(rookies[0].name);
  const [agendaChoice, setAgendaChoice] = useState("film");
  const [proposal, setProposal] = useState("");
  const set = (patch: Partial<ExpansionState>, message?: string) => { setState((current) => { const next = { ...current, ...patch }; localStorage.setItem("rimline-expansion-desk", JSON.stringify(next)); return next; }); if (message) { setProposal(message); onToast?.(message); } };
  const nav = mode === "player" ? ["overview", "calendar", "development", "contract", "records"] : ["overview", "rotation", "transactions", "scouting", "records"];
  const modifiers = useMemo(() => [
    { label: "FORM", value: clamp(58 + ((state.seed + playerWins) % 31)), tone: "cyan", note: "Last ten game signal" },
    { label: "TRUST", value: clamp(trust + state.development), tone: "gold", note: "Coach role confidence" },
    { label: "FATIGUE", value: clamp(100 - fatigue), tone: "orange", note: injuryStatus === "Healthy" ? "Lower is safer" : injuryStatus.toUpperCase() },
    { label: "FIT", value: clamp(71 + ((playerOverall + capSpace) % 22)), tone: "green", note: activeChallenge === "No active challenge" ? (mode === "player" ? "System compatibility" : "Roster balance") : activeChallenge },
  ], [state.seed, state.development, playerWins, playerOverall, capSpace, mode, fatigue, trust, injuryStatus, activeChallenge]);
  const scoutingPool = rookieClass.length ? rookieClass : rookies;
  const currentRookie = scoutingPool.find((item) => item.name === selectedRookie) || scoutingPool[0];
  const sortedRoster = [...(roster.length ? roster : [{ name: "Jayson Tatum", role: "SF", overall: 90, morale: 78 }, { name: "Jaylen Brown", role: "SG", overall: 88, morale: 84 }, { name: "Al Horford", role: "C", overall: 79, morale: 71 }, { name: "Derrick White", role: "PG", overall: 82, morale: 86 }])].sort((a, b) => state.rotationFocus === "Lockdown" ? b.morale - a.morale : b.overall - a.overall);
  const activeTab = state.tab;
  function rollWeek() { const nextSeed = (state.seed * 1103515245 + 12345) % 2147483647; set({ seed: Math.abs(nextSeed), lastDecision: `Week seed ${Math.abs(nextSeed)} locked. Modifiers recalculated.` }, "New deterministic week loaded."); }
  function saveDecision(label: string) { set({ completed: state.completed.includes(label) ? state.completed : [...state.completed, label], lastDecision: label }); }
  function negotiate() { const bump = state.contractLeverage >= 80 ? 2.5 : state.contractLeverage >= 65 ? 1.1 : 0.4; set({ contractLeverage: clamp(state.contractLeverage + 4), lastDecision: `Agent secured a ${bump.toFixed(1)}M annual leverage bump.` }, `Negotiation logged: +$${bump.toFixed(1)}M leverage.`); }
  function proposeTrade() { const targetSalary = { "Jrue Holiday": 30.0, "OG Anunoby": 36.6, "Jarrett Allen": 20.0, "Mikal Bridges": 23.3 }[tradeTarget as "Jrue Holiday" | "OG Anunoby" | "Jarrett Allen" | "Mikal Bridges"] || 20; const outgoingSalary = { "2028 first-round pick": 0, "Rotation salary slot": 18, "Prospect package": 9 }[tradeAsset as "2028 first-round pick" | "Rotation salary slot" | "Prospect package"] || 0; const matchingRoom = capSpace + outgoingSalary; const value = scoreSeed(state.seed, state.tradeCount); const legal = matchingRoom >= targetSalary * 0.8 && matchingRoom <= targetSalary * 1.25; const accepted = legal && value >= 38; const notice = accepted ? `CPU proposal accepted: ${tradeTarget} ($${targetSalary.toFixed(1)}M) for ${tradeAsset}. Fit score ${value}.` : legal ? `CPU proposal tabled: ${tradeTarget} passed salary matching, but the fit score was ${value}.` : `Trade rejected: ${tradeAsset} offers $${matchingRoom.toFixed(1)}M of matching room for a $${targetSalary.toFixed(1)}M target.`; set({ tradeCount: accepted ? state.tradeCount + 1 : state.tradeCount, lastDecision: notice }, notice); setTradeNotice(notice); }
  return <section className="expansion-desk">
    <div className="expansion-head"><div><div className="eyebrow gold-label">{mode === "player" ? "PLAYER CAREER LAB" : "FRONT OFFICE LAB"}</div><h2>THE EXPANSION DESK</h2><p>One screen for the decisions that make the next week matter.</p></div><button className="icon-button" aria-label="Roll deterministic week" onClick={rollWeek}><Dices size={18} /></button></div>
    <div className="expansion-nav" role="tablist">{nav.map((item) => <button key={item} role="tab" aria-selected={activeTab === item} className={activeTab === item ? "active" : ""} onClick={() => set({ tab: item })}>{item}</button>)}</div>
    {activeTab === "overview" && <div className="expansion-grid">
      <div className="expansion-panel wide"><div className="panel-label"><Flame size={15} /> WEEKLY MODIFIER LEDGER <span>SEED {state.seed}</span></div><div className="modifier-grid">{modifiers.map((item) => <div className={`modifier-cell ${item.tone}`} key={item.label}><strong>{item.value}</strong><span>{item.label}</span><small>{item.note}</small><i style={{ width: `${item.value}%` }} /></div>)}</div></div>
      <div className="expansion-panel"><div className="panel-label"><CalendarDays size={15} /> NEXT DECISION</div><strong className="panel-title">{mode === "player" ? "Protect the body or sharpen the edge" : "Set the rotation before the road trip"}</strong><p className="panel-copy">{state.lastDecision}</p><div className="choice-stack">{(mode === "player" ? [["film", "Film room", "+2 trust • +1 form"], ["recovery", "Recovery block", "+12 energy • -1 development"], ["community", "Community stop", "+4 reputation • -$2K"]] : [["balanced", "Keep balance", "+2 chemistry"], ["Lockdown", "Load the defense", "+3 defense • -2 pace"], ["Run & Gun", "Open the floor", "+4 offense • -2 fatigue"]]).map(([value, label, detail]) => <button key={value} className={agendaChoice === value ? "choice selected" : "choice"} onClick={() => { setAgendaChoice(value); saveDecision(label); }}>{<span>{label}<small>{detail}</small></span>}<Check size={15} /></button>)}</div></div>
      <div className="expansion-panel"><div className="panel-label"><Target size={15} /> CAREER OBJECTIVE</div><strong className="panel-title">{mode === "player" ? "Earn an All-League role" : "Turn the roster into a top-four defense"}</strong><p className="panel-copy">{playerWins} wins logged • {state.completed.length} weekly decisions recorded</p><div className="objective-bar"><i style={{ width: `${Math.min(100, 32 + playerWins)}%` }} /></div><button className="text-cta" onClick={() => set({ tab: mode === "player" ? "development" : "rotation" })}>OPEN PLAN <ArrowRightLeft size={14} /></button></div>
    </div>}
    {activeTab === "calendar" && mode === "player" && <div className="expansion-panel"><div className="panel-label"><CalendarDays size={15} /> CAREER CALENDAR</div><div className="calendar-strip">{["MON", "TUE", "WED", "THU", "FRI", "SAT", "SUN"].map((day, index) => <div className={index === 3 ? "calendar-day current" : "calendar-day"} key={day}><span>{day}</span><strong>{14 + index}</strong><small>{index === 3 ? "GAME" : index === 1 ? "FILM" : index === 5 ? "TRAVEL" : "OPEN"}</small></div>)}</div><div className="agenda-summary"><div><span>THIS WEEK</span><strong>Game 28 / 82</strong></div><div><span>ROAD LOAD</span><strong>2 away • 1 rest</strong></div><div><span>CONTRACT</span><strong>{state.contractLeverage} leverage</strong></div></div><div className="choice-stack"><button className="choice selected" onClick={() => saveDecision("Agenda locked: film room before Game 28")}>Film room before Game 28 <Check size={15} /></button><button className="choice" onClick={() => saveDecision("Agenda locked: recovery day after Game 28")}>Recovery day after Game 28 <Check size={15} /></button></div></div>}
    {activeTab === "development" && mode === "player" && <div className="expansion-grid"><div className="expansion-panel wide"><div className="panel-label"><Dumbbell size={15} /> DEVELOPMENT PLAN</div><div className="development-hero"><strong>{state.development}</strong><span>UPGRADES AVAILABLE</span><p>Choose a focus. Every upgrade is logged locally and persists with the career file.</p></div><div className="skill-list">{[["Shooting", 74], ["Playmaking", 62], ["Defense", 58], ["Athleticism", 69], ["Leadership", 44]].map(([label, value]) => <button className="skill-row" key={label} onClick={() => { set({ development: Math.max(0, state.development - 1) }, `${label} plan upgraded.`); }}><span>{label}<small>{Number(value) + (state.completed.includes(`${label} plan upgraded.`) ? 2 : 0)} / 99</small></span><i><b style={{ width: `${Number(value)}%` }} /></i><ArrowRightLeft size={14} /></button>)}</div></div><div className="expansion-panel"><div className="panel-label"><GitBranch size={15} /> POTENTIAL & AGING</div><strong className="panel-title">{playerName}</strong><p className="panel-copy">Current rating {playerOverall}. Potential band: {playerOverall + 7}–{playerOverall + 13}. Skill work remains valuable as athleticism changes.</p><div className="potential-band"><span>NOW</span><i style={{ width: `${playerOverall}%` }} /><span>CEILING</span></div><button className="text-cta" onClick={() => saveDecision("Development plan reviewed")}>LOCK PLAN <Check size={14} /></button></div></div>}
    {activeTab === "contract" && mode === "player" && <div className="expansion-grid"><div className="expansion-panel wide"><div className="panel-label"><FileText size={15} /> CONTRACT DESK</div><div className="contract-hero"><strong>${(state.contractLeverage / 5 + 8).toFixed(1)}M</strong><span>EST. ANNUAL LEVERAGE</span><p>{team} • {playerName} • {state.contractLeverage}/99 negotiating position</p></div><div className="contract-terms"><div><span>TERM</span><strong>3 years</strong></div><div><span>ROLE</span><strong>Starter track</strong></div><div><span>INCENTIVE</span><strong>All-League +$1.8M</strong></div></div><button className="primary-cta" onClick={negotiate}>NEGOTIATE WITH AGENT <ArrowRightLeft size={15} /></button></div><div className="expansion-panel"><div className="panel-label"><CircleDollarSign size={15} /> OFFER SIGNAL</div><strong className="panel-title">Two teams are tracking the fit</strong><p className="panel-copy">Leverage rises when form, durability, and role clarity stay aligned.</p>{["Boston Celtics", "New York Knicks", "Oklahoma City Thunder"].map((name, index) => <div className="offer-row" key={name}><span>{name}<small>{index === 0 ? "Continuity" : index === 1 ? "Bigger market" : "Development runway"}</small></span><strong>${(10.8 + index * 2.1).toFixed(1)}M</strong></div>)}</div></div>}
    {activeTab === "rotation" && mode === "manager" && <div className="expansion-grid"><div className="expansion-panel wide"><div className="panel-label"><Users size={15} /> ROTATION PLANNER</div><div className="choice-stack">{["Balanced", "Lockdown", "Run & Gun"].map((focus) => <button className={state.rotationFocus === focus ? "choice selected" : "choice"} key={focus} onClick={() => set({ rotationFocus: focus }, `${focus} rotation installed.`)}><span>{focus}<small>{focus === "Lockdown" ? "Prioritize morale and defensive trust" : focus === "Run & Gun" ? "Prioritize pace and scoring" : "Use the strongest full lineup"}</small></span><Check size={15} /></button>)}</div><div className="rotation-list">{sortedRoster.map((member, index) => <div className="rotation-row" key={member.name}><b>{String(index + 1).padStart(2, "0")}</b><span><strong>{member.name}</strong><small>{index < 5 ? "STARTER / CLOSER" : "BENCH UNIT"} • {member.role}</small></span><em>{member.overall}</em></div>)}</div></div><div className="expansion-panel"><div className="panel-label"><Shield size={15} /> TEAM HEALTH</div><strong className="panel-title">{team}</strong><p className="panel-copy">Chemistry 72 • Morale 81 • Defense {state.rotationFocus === "Lockdown" ? "82" : "78"}</p><div className="objective-bar"><i style={{ width: state.rotationFocus === "Lockdown" ? "82%" : "72%" }} /></div><button className="text-cta" onClick={() => saveDecision("Closing lineup reviewed")}>REVIEW CLOSERS <ArrowRightLeft size={14} /></button></div></div>}
    {activeTab === "transactions" && mode === "manager" && <div className="expansion-grid"><div className="expansion-panel wide"><div className="panel-label"><ArrowRightLeft size={15} /> TRADE MACHINE <span>{state.tradeCount} MOVES LOGGED</span></div><div className="trade-form"><label>Incoming target<select value={tradeTarget} onChange={(event) => setTradeTarget(event.target.value)}><option>Jrue Holiday</option><option>OG Anunoby</option><option>Jarrett Allen</option><option>Mikal Bridges</option></select></label><label>Outgoing asset<select value={tradeAsset} onChange={(event) => setTradeAsset(event.target.value)}><option>2028 first-round pick</option><option>Rotation salary slot</option><option>Prospect package</option></select></label></div><div className="trade-check"><span>CAP ROOM</span><strong>${capSpace}M</strong><span>MATCHING ROOM</span><strong>${(capSpace + ({ "2028 first-round pick": 0, "Rotation salary slot": 18, "Prospect package": 9 }[tradeAsset as "2028 first-round pick" | "Rotation salary slot" | "Prospect package"] || 0)).toFixed(1)}M</strong><span>SALARY CHECK</span><strong className={capSpace + ({ "2028 first-round pick": 0, "Rotation salary slot": 18, "Prospect package": 9 }[tradeAsset as "2028 first-round pick" | "Rotation salary slot" | "Prospect package"] || 0) >= ({ "Jrue Holiday": 30, "OG Anunoby": 36.6, "Jarrett Allen": 20, "Mikal Bridges": 23.3 }[tradeTarget as "Jrue Holiday" | "OG Anunoby" | "Jarrett Allen" | "Mikal Bridges"] || 20) * 0.8 ? "good" : "warn"}>{capSpace + ({ "2028 first-round pick": 0, "Rotation salary slot": 18, "Prospect package": 9 }[tradeAsset as "2028 first-round pick" | "Rotation salary slot" | "Prospect package"] || 0) >= ({ "Jrue Holiday": 30, "OG Anunoby": 36.6, "Jarrett Allen": 20, "Mikal Bridges": 23.3 }[tradeTarget as "Jrue Holiday" | "OG Anunoby" | "Jarrett Allen" | "Mikal Bridges"] || 20) * 0.8 ? "LEGAL BAND" : "REVIEW"}</strong></div><button className="primary-cta" onClick={proposeTrade}>RUN CPU PROPOSAL <Dices size={15} /></button>{tradeNotice && <div className="decision-note"><Check size={15} /> {tradeNotice}</div>}</div><div className="expansion-panel"><div className="panel-label"><CircleDollarSign size={15} /> ASSET BOARD</div><div className="asset-row"><span>Cap space</span><strong>${capSpace}M</strong></div><div className="asset-row"><span>Future firsts</span><strong>3</strong></div><div className="asset-row"><span>Trade value</span><strong>{scoreSeed(state.seed, 2)}</strong></div><p className="panel-copy">Pick protections and roster legality are surfaced before a move is accepted.</p></div></div>}
    {activeTab === "scouting" && mode === "manager" && <div className="expansion-panel"><div className="panel-label"><Sparkles size={15} /> ROOKIE CLASS BOARD <span>SEASON {Math.floor(state.seed % 10) + 1}</span></div><div className="rookie-list">{scoutingPool.map((rookie) => <button key={rookie.name} className={selectedRookie === rookie.name ? "rookie-row selected" : "rookie-row"} onClick={() => setSelectedRookie(rookie.name)}><span><strong>{rookie.name}</strong><small>{rookie.school} • {rookie.role}</small></span><b>{rookie.overall}</b><em>{rookie.potential} POT</em></button>)}</div><div className="scout-detail"><div className="panel-label"><WandSparkles size={15} /> SCOUTING READ</div><strong>{currentRookie.name}</strong><p>{currentRookie.role} from {currentRookie.school}. Current {currentRookie.overall}, potential {currentRookie.potential}, roster fit {currentRookie.fit}. Scouting uncertainty is reduced by staff investment.</p><button className="text-cta" onClick={() => saveDecision(`Scouted ${currentRookie.name}`)}>INVESTIGATE PROSPECT <ArrowRightLeft size={14} /></button></div></div>}
    {activeTab === "records" && <div className="expansion-grid"><div className="expansion-panel wide"><div className="panel-label"><Medal size={15} /> RECORD BOOK</div><div className="record-grid"><div><strong>{playerWins}</strong><span>WINS THIS RUN</span></div><div><strong>{state.completed.length}</strong><span>DECISIONS LOGGED</span></div><div><strong>{state.tradeCount}</strong><span>TRADES LOGGED</span></div><div><strong>{state.development}</strong><span>UPGRADES LEFT</span></div></div><div className="award-list">{awards.map(([label, name, line]) => <div className="award-row" key={label}><Trophy size={16} /><span><strong>{label} • {name}</strong><small>{line}</small></span><Crown size={15} /></div>)}</div></div><div className="expansion-panel"><div className="panel-label"><RotateCcw size={15} /> REPLAY LOG</div><p className="panel-copy">Deterministic week replay is ready. Roll a new seed to compare outcomes without touching the career file.</p><button className="secondary-cta" onClick={rollWeek}>ROLL NEW WEEK <Dices size={14} /></button></div></div>}
  </section>;
}
/* RIMLINE Tactical Courtbook — end expansion desk. */
